//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.efu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * EFU 37, 53, 59 (SS, FV, CD) segments.
 * 
 * <p>Java class for FraudEfu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FraudEfu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/efu}FraudType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LegalVerbiage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="FraudAdvisorIndex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudAdvisorWarningCode1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudAdvisorWarningCode2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudAdvisorWarningCode3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudAdvisorWarningCode4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudAdvisorRejectCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FirstNameCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LastNameCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BusinessNameCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StreetAddressCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SsnCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HomePhoneNumberCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="WorkPhoneNumberCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOfBirthConfirmed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DriversLicenseNumberConfirmed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EmailAddressConfirmed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SsnVerificationLevel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VerifiedFieldsGreaterThanZero" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SumOfVerificationCounters" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdAdvisorIndex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdAdvisorWarningCode1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdAdvisorWarningCode2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdAdvisorWarningCode3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdAdvisorWarningCode4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="City" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="State" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Ssn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HomePhone" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MemberFirmCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CustomerNumberAndSecurityDigits" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CdcTransactionDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CdcTransactionTime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CdcResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CdcProblemCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MatchCodes" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProblemReportDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IssueSource" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IssueIdOrReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OfacCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MdbSubjectsAge" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MdbSubjectsSsn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MdbSubjectsSsnVerified" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="InqrSubjectsSsn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="InqrSsnDateIssued" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="InqrSsnStateIssued" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="InqrSsnDeathDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="InqrSsnStateOfDeath" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SocialMatchFlags" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FraudEfu", propOrder = {
    "comment",
    "legalVerbiage"
})
public class FraudEfu
    extends FraudType
{

    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "LegalVerbiage")
    protected String legalVerbiage;
    @XmlAttribute(name = "FraudAdvisorIndex")
    protected String fraudAdvisorIndex;
    @XmlAttribute(name = "FraudAdvisorWarningCode1")
    protected String fraudAdvisorWarningCode1;
    @XmlAttribute(name = "FraudAdvisorWarningCode2")
    protected String fraudAdvisorWarningCode2;
    @XmlAttribute(name = "FraudAdvisorWarningCode3")
    protected String fraudAdvisorWarningCode3;
    @XmlAttribute(name = "FraudAdvisorWarningCode4")
    protected String fraudAdvisorWarningCode4;
    @XmlAttribute(name = "FraudAdvisorRejectCode")
    protected String fraudAdvisorRejectCode;
    @XmlAttribute(name = "FirstNameCounter")
    protected String firstNameCounter;
    @XmlAttribute(name = "LastNameCounter")
    protected String lastNameCounter;
    @XmlAttribute(name = "BusinessNameCounter")
    protected String businessNameCounter;
    @XmlAttribute(name = "StreetAddressCounter")
    protected String streetAddressCounter;
    @XmlAttribute(name = "SsnCounter")
    protected String ssnCounter;
    @XmlAttribute(name = "HomePhoneNumberCounter")
    protected String homePhoneNumberCounter;
    @XmlAttribute(name = "WorkPhoneNumberCounter")
    protected String workPhoneNumberCounter;
    @XmlAttribute(name = "DateOfBirthConfirmed")
    protected String dateOfBirthConfirmed;
    @XmlAttribute(name = "DriversLicenseNumberConfirmed")
    protected String driversLicenseNumberConfirmed;
    @XmlAttribute(name = "EmailAddressConfirmed")
    protected String emailAddressConfirmed;
    @XmlAttribute(name = "SsnVerificationLevel")
    protected String ssnVerificationLevel;
    @XmlAttribute(name = "VerifiedFieldsGreaterThanZero")
    protected String verifiedFieldsGreaterThanZero;
    @XmlAttribute(name = "SumOfVerificationCounters")
    protected String sumOfVerificationCounters;
    @XmlAttribute(name = "IdAdvisorIndex")
    protected String idAdvisorIndex;
    @XmlAttribute(name = "IdAdvisorWarningCode1")
    protected String idAdvisorWarningCode1;
    @XmlAttribute(name = "IdAdvisorWarningCode2")
    protected String idAdvisorWarningCode2;
    @XmlAttribute(name = "IdAdvisorWarningCode3")
    protected String idAdvisorWarningCode3;
    @XmlAttribute(name = "IdAdvisorWarningCode4")
    protected String idAdvisorWarningCode4;
    @XmlAttribute(name = "FirstName")
    protected String firstName;
    @XmlAttribute(name = "MiddleName")
    protected String middleName;
    @XmlAttribute(name = "LastName")
    protected String lastName;
    @XmlAttribute(name = "StreetAddress")
    protected String streetAddress;
    @XmlAttribute(name = "City")
    protected String city;
    @XmlAttribute(name = "State")
    protected String state;
    @XmlAttribute(name = "ZipCode")
    protected String zipCode;
    @XmlAttribute(name = "Ssn")
    protected String ssn;
    @XmlAttribute(name = "DateOfBirth")
    protected String dateOfBirth;
    @XmlAttribute(name = "HomePhone")
    protected String homePhone;
    @XmlAttribute(name = "MemberFirmCode")
    protected String memberFirmCode;
    @XmlAttribute(name = "CustomerNumberAndSecurityDigits")
    protected String customerNumberAndSecurityDigits;
    @XmlAttribute(name = "CdcTransactionDate")
    protected String cdcTransactionDate;
    @XmlAttribute(name = "CdcTransactionTime")
    protected String cdcTransactionTime;
    @XmlAttribute(name = "TransactionType")
    protected String transactionType;
    @XmlAttribute(name = "CdcResponseCode")
    protected String cdcResponseCode;
    @XmlAttribute(name = "CdcProblemCode")
    protected String cdcProblemCode;
    @XmlAttribute(name = "MatchCodes")
    protected String matchCodes;
    @XmlAttribute(name = "ProblemReportDate")
    protected String problemReportDate;
    @XmlAttribute(name = "IssueSource")
    protected String issueSource;
    @XmlAttribute(name = "IssueIdOrReference")
    protected String issueIdOrReference;
    @XmlAttribute(name = "OfacCountryCode")
    protected String ofacCountryCode;
    @XmlAttribute(name = "MdbSubjectsAge")
    protected String mdbSubjectsAge;
    @XmlAttribute(name = "MdbSubjectsSsn")
    protected String mdbSubjectsSsn;
    @XmlAttribute(name = "MdbSubjectsSsnVerified")
    protected String mdbSubjectsSsnVerified;
    @XmlAttribute(name = "InqrSubjectsSsn")
    protected String inqrSubjectsSsn;
    @XmlAttribute(name = "InqrSsnDateIssued")
    protected String inqrSsnDateIssued;
    @XmlAttribute(name = "InqrSsnStateIssued")
    protected String inqrSsnStateIssued;
    @XmlAttribute(name = "InqrSsnDeathDate")
    protected String inqrSsnDeathDate;
    @XmlAttribute(name = "InqrSsnStateOfDeath")
    protected String inqrSsnStateOfDeath;
    @XmlAttribute(name = "SocialMatchFlags")
    protected String socialMatchFlags;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the legalVerbiage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalVerbiage() {
        return legalVerbiage;
    }

    /**
     * Sets the value of the legalVerbiage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalVerbiage(String value) {
        this.legalVerbiage = value;
    }

    /**
     * Gets the value of the fraudAdvisorIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorIndex() {
        return fraudAdvisorIndex;
    }

    /**
     * Sets the value of the fraudAdvisorIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorIndex(String value) {
        this.fraudAdvisorIndex = value;
    }

    /**
     * Gets the value of the fraudAdvisorWarningCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorWarningCode1() {
        return fraudAdvisorWarningCode1;
    }

    /**
     * Sets the value of the fraudAdvisorWarningCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorWarningCode1(String value) {
        this.fraudAdvisorWarningCode1 = value;
    }

    /**
     * Gets the value of the fraudAdvisorWarningCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorWarningCode2() {
        return fraudAdvisorWarningCode2;
    }

    /**
     * Sets the value of the fraudAdvisorWarningCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorWarningCode2(String value) {
        this.fraudAdvisorWarningCode2 = value;
    }

    /**
     * Gets the value of the fraudAdvisorWarningCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorWarningCode3() {
        return fraudAdvisorWarningCode3;
    }

    /**
     * Sets the value of the fraudAdvisorWarningCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorWarningCode3(String value) {
        this.fraudAdvisorWarningCode3 = value;
    }

    /**
     * Gets the value of the fraudAdvisorWarningCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorWarningCode4() {
        return fraudAdvisorWarningCode4;
    }

    /**
     * Sets the value of the fraudAdvisorWarningCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorWarningCode4(String value) {
        this.fraudAdvisorWarningCode4 = value;
    }

    /**
     * Gets the value of the fraudAdvisorRejectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudAdvisorRejectCode() {
        return fraudAdvisorRejectCode;
    }

    /**
     * Sets the value of the fraudAdvisorRejectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudAdvisorRejectCode(String value) {
        this.fraudAdvisorRejectCode = value;
    }

    /**
     * Gets the value of the firstNameCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNameCounter() {
        return firstNameCounter;
    }

    /**
     * Sets the value of the firstNameCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNameCounter(String value) {
        this.firstNameCounter = value;
    }

    /**
     * Gets the value of the lastNameCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNameCounter() {
        return lastNameCounter;
    }

    /**
     * Sets the value of the lastNameCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNameCounter(String value) {
        this.lastNameCounter = value;
    }

    /**
     * Gets the value of the businessNameCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessNameCounter() {
        return businessNameCounter;
    }

    /**
     * Sets the value of the businessNameCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessNameCounter(String value) {
        this.businessNameCounter = value;
    }

    /**
     * Gets the value of the streetAddressCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddressCounter() {
        return streetAddressCounter;
    }

    /**
     * Sets the value of the streetAddressCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddressCounter(String value) {
        this.streetAddressCounter = value;
    }

    /**
     * Gets the value of the ssnCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsnCounter() {
        return ssnCounter;
    }

    /**
     * Sets the value of the ssnCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsnCounter(String value) {
        this.ssnCounter = value;
    }

    /**
     * Gets the value of the homePhoneNumberCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhoneNumberCounter() {
        return homePhoneNumberCounter;
    }

    /**
     * Sets the value of the homePhoneNumberCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhoneNumberCounter(String value) {
        this.homePhoneNumberCounter = value;
    }

    /**
     * Gets the value of the workPhoneNumberCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhoneNumberCounter() {
        return workPhoneNumberCounter;
    }

    /**
     * Sets the value of the workPhoneNumberCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhoneNumberCounter(String value) {
        this.workPhoneNumberCounter = value;
    }

    /**
     * Gets the value of the dateOfBirthConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirthConfirmed() {
        return dateOfBirthConfirmed;
    }

    /**
     * Sets the value of the dateOfBirthConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirthConfirmed(String value) {
        this.dateOfBirthConfirmed = value;
    }

    /**
     * Gets the value of the driversLicenseNumberConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicenseNumberConfirmed() {
        return driversLicenseNumberConfirmed;
    }

    /**
     * Sets the value of the driversLicenseNumberConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicenseNumberConfirmed(String value) {
        this.driversLicenseNumberConfirmed = value;
    }

    /**
     * Gets the value of the emailAddressConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddressConfirmed() {
        return emailAddressConfirmed;
    }

    /**
     * Sets the value of the emailAddressConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddressConfirmed(String value) {
        this.emailAddressConfirmed = value;
    }

    /**
     * Gets the value of the ssnVerificationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsnVerificationLevel() {
        return ssnVerificationLevel;
    }

    /**
     * Sets the value of the ssnVerificationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsnVerificationLevel(String value) {
        this.ssnVerificationLevel = value;
    }

    /**
     * Gets the value of the verifiedFieldsGreaterThanZero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifiedFieldsGreaterThanZero() {
        return verifiedFieldsGreaterThanZero;
    }

    /**
     * Sets the value of the verifiedFieldsGreaterThanZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifiedFieldsGreaterThanZero(String value) {
        this.verifiedFieldsGreaterThanZero = value;
    }

    /**
     * Gets the value of the sumOfVerificationCounters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSumOfVerificationCounters() {
        return sumOfVerificationCounters;
    }

    /**
     * Sets the value of the sumOfVerificationCounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSumOfVerificationCounters(String value) {
        this.sumOfVerificationCounters = value;
    }

    /**
     * Gets the value of the idAdvisorIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAdvisorIndex() {
        return idAdvisorIndex;
    }

    /**
     * Sets the value of the idAdvisorIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAdvisorIndex(String value) {
        this.idAdvisorIndex = value;
    }

    /**
     * Gets the value of the idAdvisorWarningCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAdvisorWarningCode1() {
        return idAdvisorWarningCode1;
    }

    /**
     * Sets the value of the idAdvisorWarningCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAdvisorWarningCode1(String value) {
        this.idAdvisorWarningCode1 = value;
    }

    /**
     * Gets the value of the idAdvisorWarningCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAdvisorWarningCode2() {
        return idAdvisorWarningCode2;
    }

    /**
     * Sets the value of the idAdvisorWarningCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAdvisorWarningCode2(String value) {
        this.idAdvisorWarningCode2 = value;
    }

    /**
     * Gets the value of the idAdvisorWarningCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAdvisorWarningCode3() {
        return idAdvisorWarningCode3;
    }

    /**
     * Sets the value of the idAdvisorWarningCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAdvisorWarningCode3(String value) {
        this.idAdvisorWarningCode3 = value;
    }

    /**
     * Gets the value of the idAdvisorWarningCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAdvisorWarningCode4() {
        return idAdvisorWarningCode4;
    }

    /**
     * Sets the value of the idAdvisorWarningCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAdvisorWarningCode4(String value) {
        this.idAdvisorWarningCode4 = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhone(String value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the memberFirmCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberFirmCode() {
        return memberFirmCode;
    }

    /**
     * Sets the value of the memberFirmCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberFirmCode(String value) {
        this.memberFirmCode = value;
    }

    /**
     * Gets the value of the customerNumberAndSecurityDigits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumberAndSecurityDigits() {
        return customerNumberAndSecurityDigits;
    }

    /**
     * Sets the value of the customerNumberAndSecurityDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumberAndSecurityDigits(String value) {
        this.customerNumberAndSecurityDigits = value;
    }

    /**
     * Gets the value of the cdcTransactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdcTransactionDate() {
        return cdcTransactionDate;
    }

    /**
     * Sets the value of the cdcTransactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdcTransactionDate(String value) {
        this.cdcTransactionDate = value;
    }

    /**
     * Gets the value of the cdcTransactionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdcTransactionTime() {
        return cdcTransactionTime;
    }

    /**
     * Sets the value of the cdcTransactionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdcTransactionTime(String value) {
        this.cdcTransactionTime = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the cdcResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdcResponseCode() {
        return cdcResponseCode;
    }

    /**
     * Sets the value of the cdcResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdcResponseCode(String value) {
        this.cdcResponseCode = value;
    }

    /**
     * Gets the value of the cdcProblemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdcProblemCode() {
        return cdcProblemCode;
    }

    /**
     * Sets the value of the cdcProblemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdcProblemCode(String value) {
        this.cdcProblemCode = value;
    }

    /**
     * Gets the value of the matchCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchCodes() {
        return matchCodes;
    }

    /**
     * Sets the value of the matchCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchCodes(String value) {
        this.matchCodes = value;
    }

    /**
     * Gets the value of the problemReportDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProblemReportDate() {
        return problemReportDate;
    }

    /**
     * Sets the value of the problemReportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProblemReportDate(String value) {
        this.problemReportDate = value;
    }

    /**
     * Gets the value of the issueSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueSource() {
        return issueSource;
    }

    /**
     * Sets the value of the issueSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueSource(String value) {
        this.issueSource = value;
    }

    /**
     * Gets the value of the issueIdOrReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueIdOrReference() {
        return issueIdOrReference;
    }

    /**
     * Sets the value of the issueIdOrReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueIdOrReference(String value) {
        this.issueIdOrReference = value;
    }

    /**
     * Gets the value of the ofacCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfacCountryCode() {
        return ofacCountryCode;
    }

    /**
     * Sets the value of the ofacCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfacCountryCode(String value) {
        this.ofacCountryCode = value;
    }

    /**
     * Gets the value of the mdbSubjectsAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdbSubjectsAge() {
        return mdbSubjectsAge;
    }

    /**
     * Sets the value of the mdbSubjectsAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdbSubjectsAge(String value) {
        this.mdbSubjectsAge = value;
    }

    /**
     * Gets the value of the mdbSubjectsSsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdbSubjectsSsn() {
        return mdbSubjectsSsn;
    }

    /**
     * Sets the value of the mdbSubjectsSsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdbSubjectsSsn(String value) {
        this.mdbSubjectsSsn = value;
    }

    /**
     * Gets the value of the mdbSubjectsSsnVerified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdbSubjectsSsnVerified() {
        return mdbSubjectsSsnVerified;
    }

    /**
     * Sets the value of the mdbSubjectsSsnVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdbSubjectsSsnVerified(String value) {
        this.mdbSubjectsSsnVerified = value;
    }

    /**
     * Gets the value of the inqrSubjectsSsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqrSubjectsSsn() {
        return inqrSubjectsSsn;
    }

    /**
     * Sets the value of the inqrSubjectsSsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqrSubjectsSsn(String value) {
        this.inqrSubjectsSsn = value;
    }

    /**
     * Gets the value of the inqrSsnDateIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqrSsnDateIssued() {
        return inqrSsnDateIssued;
    }

    /**
     * Sets the value of the inqrSsnDateIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqrSsnDateIssued(String value) {
        this.inqrSsnDateIssued = value;
    }

    /**
     * Gets the value of the inqrSsnStateIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqrSsnStateIssued() {
        return inqrSsnStateIssued;
    }

    /**
     * Sets the value of the inqrSsnStateIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqrSsnStateIssued(String value) {
        this.inqrSsnStateIssued = value;
    }

    /**
     * Gets the value of the inqrSsnDeathDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqrSsnDeathDate() {
        return inqrSsnDeathDate;
    }

    /**
     * Sets the value of the inqrSsnDeathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqrSsnDeathDate(String value) {
        this.inqrSsnDeathDate = value;
    }

    /**
     * Gets the value of the inqrSsnStateOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqrSsnStateOfDeath() {
        return inqrSsnStateOfDeath;
    }

    /**
     * Sets the value of the inqrSsnStateOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqrSsnStateOfDeath(String value) {
        this.inqrSsnStateOfDeath = value;
    }

    /**
     * Gets the value of the socialMatchFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialMatchFlags() {
        return socialMatchFlags;
    }

    /**
     * Sets the value of the socialMatchFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialMatchFlags(String value) {
        this.socialMatchFlags = value;
    }

}
