//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.efu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * EFU FULL, CERR, MERR segments.
 * 
 * <p>Java class for HeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute ref="{http://fico.com/dms/fidms/cc/cdac/efu}Bureau"/&gt;
 *       &lt;attribute ref="{http://fico.com/dms/fidms/cc/cdac/efu}SourceSegment"/&gt;
 *       &lt;attribute name="DateOfThisReport" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BureauArfVersion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UserReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType")
@XmlSeeAlso({
    HeaderEfu.class
})
public class HeaderType {

    @XmlAttribute(name = "Bureau", namespace = "http://fico.com/dms/fidms/cc/cdac/efu")
    protected String bureau;
    @XmlAttribute(name = "SourceSegment", namespace = "http://fico.com/dms/fidms/cc/cdac/efu")
    protected String sourceSegment;
    @XmlAttribute(name = "DateOfThisReport")
    protected String dateOfThisReport;
    @XmlAttribute(name = "BureauArfVersion")
    protected String bureauArfVersion;
    @XmlAttribute(name = "UserReference")
    protected String userReference;

    /**
     * EFU Bureau Indicator
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureau() {
        return bureau;
    }

    /**
     * Sets the value of the bureau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureau(String value) {
        this.bureau = value;
    }

    /**
     * EFU Source Segment
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSegment() {
        return sourceSegment;
    }

    /**
     * Sets the value of the sourceSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSegment(String value) {
        this.sourceSegment = value;
    }

    /**
     * Gets the value of the dateOfThisReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfThisReport() {
        return dateOfThisReport;
    }

    /**
     * Sets the value of the dateOfThisReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfThisReport(String value) {
        this.dateOfThisReport = value;
    }

    /**
     * Gets the value of the bureauArfVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauArfVersion() {
        return bureauArfVersion;
    }

    /**
     * Sets the value of the bureauArfVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauArfVersion(String value) {
        this.bureauArfVersion = value;
    }

    /**
     * Gets the value of the userReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReference() {
        return userReference;
    }

    /**
     * Sets the value of the userReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReference(String value) {
        this.userReference = value;
    }

}
