//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.efu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * EFU FULL, CERR, MERR segments.
 * 
 * <p>Java class for HeaderEfu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderEfu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/efu}HeaderType"&gt;
 *       &lt;attribute name="SubscriberNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ConsumerReferralCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MultipleFileIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FileNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EcoaInquiryType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberMonthsToCountInquiries" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberMonthsToCountMaxDelinquentMethodOfPayment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HitOrNoHitDesignatorCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FileSinceDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOfLastActivity" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LinkIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DoNotCombineIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfAdditionalMultiples" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SegmentCounters" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BusinessSolutionsData" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FirstNameMatchFlag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MiddleNameMatch" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LastNameMatchFlag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SuffixMatchFlag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SSNAffirmAlertFlag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IdentityScanIndicatorCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ErrorMessageCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ErrorCodeVerbiage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfFormatErrors" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode6" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode7" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode8" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FormatErrorCode9" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfValidityErrors" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode6" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode7" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode8" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ValidityErrorCode9" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfProcessingErrors" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode6" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode7" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode8" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProcessingErrorCode9" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FraudVictimIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SafescanCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CbiSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AcceptReject" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AcceptRejectCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PointScore1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PointScore2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LocateNotice" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ManualFile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UnderReview" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ConsumerStatement" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NoSolicitation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UserReference2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AddressDiscrepancyIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderEfu")
public class HeaderEfu
    extends HeaderType
{

    @XmlAttribute(name = "SubscriberNumber")
    protected String subscriberNumber;
    @XmlAttribute(name = "SecurityCode")
    protected String securityCode;
    @XmlAttribute(name = "ConsumerReferralCode")
    protected String consumerReferralCode;
    @XmlAttribute(name = "MultipleFileIndicator")
    protected String multipleFileIndicator;
    @XmlAttribute(name = "FileNumber")
    protected String fileNumber;
    @XmlAttribute(name = "EcoaInquiryType")
    protected String ecoaInquiryType;
    @XmlAttribute(name = "NumberMonthsToCountInquiries")
    protected String numberMonthsToCountInquiries;
    @XmlAttribute(name = "NumberMonthsToCountMaxDelinquentMethodOfPayment")
    protected String numberMonthsToCountMaxDelinquentMethodOfPayment;
    @XmlAttribute(name = "HitOrNoHitDesignatorCode")
    protected String hitOrNoHitDesignatorCode;
    @XmlAttribute(name = "FileSinceDate")
    protected String fileSinceDate;
    @XmlAttribute(name = "DateOfLastActivity")
    protected String dateOfLastActivity;
    @XmlAttribute(name = "LinkIndicator")
    protected String linkIndicator;
    @XmlAttribute(name = "DoNotCombineIndicator")
    protected String doNotCombineIndicator;
    @XmlAttribute(name = "NumberOfAdditionalMultiples")
    protected String numberOfAdditionalMultiples;
    @XmlAttribute(name = "SegmentCounters")
    protected String segmentCounters;
    @XmlAttribute(name = "BusinessSolutionsData")
    protected String businessSolutionsData;
    @XmlAttribute(name = "FirstNameMatchFlag")
    protected String firstNameMatchFlag;
    @XmlAttribute(name = "MiddleNameMatch")
    protected String middleNameMatch;
    @XmlAttribute(name = "LastNameMatchFlag")
    protected String lastNameMatchFlag;
    @XmlAttribute(name = "SuffixMatchFlag")
    protected String suffixMatchFlag;
    @XmlAttribute(name = "SSNAffirmAlertFlag")
    protected String ssnAffirmAlertFlag;
    @XmlAttribute(name = "IdentityScanIndicatorCode")
    protected String identityScanIndicatorCode;
    @XmlAttribute(name = "ErrorMessageCode")
    protected String errorMessageCode;
    @XmlAttribute(name = "ErrorCodeVerbiage")
    protected String errorCodeVerbiage;
    @XmlAttribute(name = "NumberOfFormatErrors")
    protected String numberOfFormatErrors;
    @XmlAttribute(name = "FormatErrorCode1")
    protected String formatErrorCode1;
    @XmlAttribute(name = "FormatErrorCode2")
    protected String formatErrorCode2;
    @XmlAttribute(name = "FormatErrorCode3")
    protected String formatErrorCode3;
    @XmlAttribute(name = "FormatErrorCode4")
    protected String formatErrorCode4;
    @XmlAttribute(name = "FormatErrorCode5")
    protected String formatErrorCode5;
    @XmlAttribute(name = "FormatErrorCode6")
    protected String formatErrorCode6;
    @XmlAttribute(name = "FormatErrorCode7")
    protected String formatErrorCode7;
    @XmlAttribute(name = "FormatErrorCode8")
    protected String formatErrorCode8;
    @XmlAttribute(name = "FormatErrorCode9")
    protected String formatErrorCode9;
    @XmlAttribute(name = "NumberOfValidityErrors")
    protected String numberOfValidityErrors;
    @XmlAttribute(name = "ValidityErrorCode1")
    protected String validityErrorCode1;
    @XmlAttribute(name = "ValidityErrorCode2")
    protected String validityErrorCode2;
    @XmlAttribute(name = "ValidityErrorCode3")
    protected String validityErrorCode3;
    @XmlAttribute(name = "ValidityErrorCode4")
    protected String validityErrorCode4;
    @XmlAttribute(name = "ValidityErrorCode5")
    protected String validityErrorCode5;
    @XmlAttribute(name = "ValidityErrorCode6")
    protected String validityErrorCode6;
    @XmlAttribute(name = "ValidityErrorCode7")
    protected String validityErrorCode7;
    @XmlAttribute(name = "ValidityErrorCode8")
    protected String validityErrorCode8;
    @XmlAttribute(name = "ValidityErrorCode9")
    protected String validityErrorCode9;
    @XmlAttribute(name = "NumberOfProcessingErrors")
    protected String numberOfProcessingErrors;
    @XmlAttribute(name = "ProcessingErrorCode1")
    protected String processingErrorCode1;
    @XmlAttribute(name = "ProcessingErrorCode2")
    protected String processingErrorCode2;
    @XmlAttribute(name = "ProcessingErrorCode3")
    protected String processingErrorCode3;
    @XmlAttribute(name = "ProcessingErrorCode4")
    protected String processingErrorCode4;
    @XmlAttribute(name = "ProcessingErrorCode5")
    protected String processingErrorCode5;
    @XmlAttribute(name = "ProcessingErrorCode6")
    protected String processingErrorCode6;
    @XmlAttribute(name = "ProcessingErrorCode7")
    protected String processingErrorCode7;
    @XmlAttribute(name = "ProcessingErrorCode8")
    protected String processingErrorCode8;
    @XmlAttribute(name = "ProcessingErrorCode9")
    protected String processingErrorCode9;
    @XmlAttribute(name = "FraudVictimIndicator")
    protected String fraudVictimIndicator;
    @XmlAttribute(name = "SafescanCode")
    protected String safescanCode;
    @XmlAttribute(name = "CbiSequenceNumber")
    protected String cbiSequenceNumber;
    @XmlAttribute(name = "AcceptReject")
    protected String acceptReject;
    @XmlAttribute(name = "AcceptRejectCode")
    protected String acceptRejectCode;
    @XmlAttribute(name = "PointScore1")
    protected String pointScore1;
    @XmlAttribute(name = "PointScore2")
    protected String pointScore2;
    @XmlAttribute(name = "LocateNotice")
    protected String locateNotice;
    @XmlAttribute(name = "ManualFile")
    protected String manualFile;
    @XmlAttribute(name = "UnderReview")
    protected String underReview;
    @XmlAttribute(name = "ConsumerStatement")
    protected String consumerStatement;
    @XmlAttribute(name = "NoSolicitation")
    protected String noSolicitation;
    @XmlAttribute(name = "UserReference2")
    protected String userReference2;
    @XmlAttribute(name = "AddressDiscrepancyIndicator")
    protected String addressDiscrepancyIndicator;

    /**
     * Gets the value of the subscriberNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberNumber() {
        return subscriberNumber;
    }

    /**
     * Sets the value of the subscriberNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberNumber(String value) {
        this.subscriberNumber = value;
    }

    /**
     * Gets the value of the securityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * Sets the value of the securityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCode(String value) {
        this.securityCode = value;
    }

    /**
     * Gets the value of the consumerReferralCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerReferralCode() {
        return consumerReferralCode;
    }

    /**
     * Sets the value of the consumerReferralCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerReferralCode(String value) {
        this.consumerReferralCode = value;
    }

    /**
     * Gets the value of the multipleFileIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleFileIndicator() {
        return multipleFileIndicator;
    }

    /**
     * Sets the value of the multipleFileIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleFileIndicator(String value) {
        this.multipleFileIndicator = value;
    }

    /**
     * Gets the value of the fileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * Sets the value of the fileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileNumber(String value) {
        this.fileNumber = value;
    }

    /**
     * Gets the value of the ecoaInquiryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcoaInquiryType() {
        return ecoaInquiryType;
    }

    /**
     * Sets the value of the ecoaInquiryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcoaInquiryType(String value) {
        this.ecoaInquiryType = value;
    }

    /**
     * Gets the value of the numberMonthsToCountInquiries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberMonthsToCountInquiries() {
        return numberMonthsToCountInquiries;
    }

    /**
     * Sets the value of the numberMonthsToCountInquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberMonthsToCountInquiries(String value) {
        this.numberMonthsToCountInquiries = value;
    }

    /**
     * Gets the value of the numberMonthsToCountMaxDelinquentMethodOfPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberMonthsToCountMaxDelinquentMethodOfPayment() {
        return numberMonthsToCountMaxDelinquentMethodOfPayment;
    }

    /**
     * Sets the value of the numberMonthsToCountMaxDelinquentMethodOfPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberMonthsToCountMaxDelinquentMethodOfPayment(String value) {
        this.numberMonthsToCountMaxDelinquentMethodOfPayment = value;
    }

    /**
     * Gets the value of the hitOrNoHitDesignatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitOrNoHitDesignatorCode() {
        return hitOrNoHitDesignatorCode;
    }

    /**
     * Sets the value of the hitOrNoHitDesignatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitOrNoHitDesignatorCode(String value) {
        this.hitOrNoHitDesignatorCode = value;
    }

    /**
     * Gets the value of the fileSinceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSinceDate() {
        return fileSinceDate;
    }

    /**
     * Sets the value of the fileSinceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSinceDate(String value) {
        this.fileSinceDate = value;
    }

    /**
     * Gets the value of the dateOfLastActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfLastActivity() {
        return dateOfLastActivity;
    }

    /**
     * Sets the value of the dateOfLastActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfLastActivity(String value) {
        this.dateOfLastActivity = value;
    }

    /**
     * Gets the value of the linkIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIndicator() {
        return linkIndicator;
    }

    /**
     * Sets the value of the linkIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIndicator(String value) {
        this.linkIndicator = value;
    }

    /**
     * Gets the value of the doNotCombineIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoNotCombineIndicator() {
        return doNotCombineIndicator;
    }

    /**
     * Sets the value of the doNotCombineIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoNotCombineIndicator(String value) {
        this.doNotCombineIndicator = value;
    }

    /**
     * Gets the value of the numberOfAdditionalMultiples property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfAdditionalMultiples() {
        return numberOfAdditionalMultiples;
    }

    /**
     * Sets the value of the numberOfAdditionalMultiples property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfAdditionalMultiples(String value) {
        this.numberOfAdditionalMultiples = value;
    }

    /**
     * Gets the value of the segmentCounters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentCounters() {
        return segmentCounters;
    }

    /**
     * Sets the value of the segmentCounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentCounters(String value) {
        this.segmentCounters = value;
    }

    /**
     * Gets the value of the businessSolutionsData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessSolutionsData() {
        return businessSolutionsData;
    }

    /**
     * Sets the value of the businessSolutionsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessSolutionsData(String value) {
        this.businessSolutionsData = value;
    }

    /**
     * Gets the value of the firstNameMatchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNameMatchFlag() {
        return firstNameMatchFlag;
    }

    /**
     * Sets the value of the firstNameMatchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNameMatchFlag(String value) {
        this.firstNameMatchFlag = value;
    }

    /**
     * Gets the value of the middleNameMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleNameMatch() {
        return middleNameMatch;
    }

    /**
     * Sets the value of the middleNameMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleNameMatch(String value) {
        this.middleNameMatch = value;
    }

    /**
     * Gets the value of the lastNameMatchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNameMatchFlag() {
        return lastNameMatchFlag;
    }

    /**
     * Sets the value of the lastNameMatchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNameMatchFlag(String value) {
        this.lastNameMatchFlag = value;
    }

    /**
     * Gets the value of the suffixMatchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffixMatchFlag() {
        return suffixMatchFlag;
    }

    /**
     * Sets the value of the suffixMatchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffixMatchFlag(String value) {
        this.suffixMatchFlag = value;
    }

    /**
     * Gets the value of the ssnAffirmAlertFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSNAffirmAlertFlag() {
        return ssnAffirmAlertFlag;
    }

    /**
     * Sets the value of the ssnAffirmAlertFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSNAffirmAlertFlag(String value) {
        this.ssnAffirmAlertFlag = value;
    }

    /**
     * Gets the value of the identityScanIndicatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityScanIndicatorCode() {
        return identityScanIndicatorCode;
    }

    /**
     * Sets the value of the identityScanIndicatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityScanIndicatorCode(String value) {
        this.identityScanIndicatorCode = value;
    }

    /**
     * Gets the value of the errorMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessageCode() {
        return errorMessageCode;
    }

    /**
     * Sets the value of the errorMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessageCode(String value) {
        this.errorMessageCode = value;
    }

    /**
     * Gets the value of the errorCodeVerbiage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCodeVerbiage() {
        return errorCodeVerbiage;
    }

    /**
     * Sets the value of the errorCodeVerbiage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCodeVerbiage(String value) {
        this.errorCodeVerbiage = value;
    }

    /**
     * Gets the value of the numberOfFormatErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfFormatErrors() {
        return numberOfFormatErrors;
    }

    /**
     * Sets the value of the numberOfFormatErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfFormatErrors(String value) {
        this.numberOfFormatErrors = value;
    }

    /**
     * Gets the value of the formatErrorCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode1() {
        return formatErrorCode1;
    }

    /**
     * Sets the value of the formatErrorCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode1(String value) {
        this.formatErrorCode1 = value;
    }

    /**
     * Gets the value of the formatErrorCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode2() {
        return formatErrorCode2;
    }

    /**
     * Sets the value of the formatErrorCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode2(String value) {
        this.formatErrorCode2 = value;
    }

    /**
     * Gets the value of the formatErrorCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode3() {
        return formatErrorCode3;
    }

    /**
     * Sets the value of the formatErrorCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode3(String value) {
        this.formatErrorCode3 = value;
    }

    /**
     * Gets the value of the formatErrorCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode4() {
        return formatErrorCode4;
    }

    /**
     * Sets the value of the formatErrorCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode4(String value) {
        this.formatErrorCode4 = value;
    }

    /**
     * Gets the value of the formatErrorCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode5() {
        return formatErrorCode5;
    }

    /**
     * Sets the value of the formatErrorCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode5(String value) {
        this.formatErrorCode5 = value;
    }

    /**
     * Gets the value of the formatErrorCode6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode6() {
        return formatErrorCode6;
    }

    /**
     * Sets the value of the formatErrorCode6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode6(String value) {
        this.formatErrorCode6 = value;
    }

    /**
     * Gets the value of the formatErrorCode7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode7() {
        return formatErrorCode7;
    }

    /**
     * Sets the value of the formatErrorCode7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode7(String value) {
        this.formatErrorCode7 = value;
    }

    /**
     * Gets the value of the formatErrorCode8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode8() {
        return formatErrorCode8;
    }

    /**
     * Sets the value of the formatErrorCode8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode8(String value) {
        this.formatErrorCode8 = value;
    }

    /**
     * Gets the value of the formatErrorCode9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatErrorCode9() {
        return formatErrorCode9;
    }

    /**
     * Sets the value of the formatErrorCode9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatErrorCode9(String value) {
        this.formatErrorCode9 = value;
    }

    /**
     * Gets the value of the numberOfValidityErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfValidityErrors() {
        return numberOfValidityErrors;
    }

    /**
     * Sets the value of the numberOfValidityErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfValidityErrors(String value) {
        this.numberOfValidityErrors = value;
    }

    /**
     * Gets the value of the validityErrorCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode1() {
        return validityErrorCode1;
    }

    /**
     * Sets the value of the validityErrorCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode1(String value) {
        this.validityErrorCode1 = value;
    }

    /**
     * Gets the value of the validityErrorCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode2() {
        return validityErrorCode2;
    }

    /**
     * Sets the value of the validityErrorCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode2(String value) {
        this.validityErrorCode2 = value;
    }

    /**
     * Gets the value of the validityErrorCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode3() {
        return validityErrorCode3;
    }

    /**
     * Sets the value of the validityErrorCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode3(String value) {
        this.validityErrorCode3 = value;
    }

    /**
     * Gets the value of the validityErrorCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode4() {
        return validityErrorCode4;
    }

    /**
     * Sets the value of the validityErrorCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode4(String value) {
        this.validityErrorCode4 = value;
    }

    /**
     * Gets the value of the validityErrorCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode5() {
        return validityErrorCode5;
    }

    /**
     * Sets the value of the validityErrorCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode5(String value) {
        this.validityErrorCode5 = value;
    }

    /**
     * Gets the value of the validityErrorCode6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode6() {
        return validityErrorCode6;
    }

    /**
     * Sets the value of the validityErrorCode6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode6(String value) {
        this.validityErrorCode6 = value;
    }

    /**
     * Gets the value of the validityErrorCode7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode7() {
        return validityErrorCode7;
    }

    /**
     * Sets the value of the validityErrorCode7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode7(String value) {
        this.validityErrorCode7 = value;
    }

    /**
     * Gets the value of the validityErrorCode8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode8() {
        return validityErrorCode8;
    }

    /**
     * Sets the value of the validityErrorCode8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode8(String value) {
        this.validityErrorCode8 = value;
    }

    /**
     * Gets the value of the validityErrorCode9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityErrorCode9() {
        return validityErrorCode9;
    }

    /**
     * Sets the value of the validityErrorCode9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityErrorCode9(String value) {
        this.validityErrorCode9 = value;
    }

    /**
     * Gets the value of the numberOfProcessingErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfProcessingErrors() {
        return numberOfProcessingErrors;
    }

    /**
     * Sets the value of the numberOfProcessingErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfProcessingErrors(String value) {
        this.numberOfProcessingErrors = value;
    }

    /**
     * Gets the value of the processingErrorCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode1() {
        return processingErrorCode1;
    }

    /**
     * Sets the value of the processingErrorCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode1(String value) {
        this.processingErrorCode1 = value;
    }

    /**
     * Gets the value of the processingErrorCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode2() {
        return processingErrorCode2;
    }

    /**
     * Sets the value of the processingErrorCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode2(String value) {
        this.processingErrorCode2 = value;
    }

    /**
     * Gets the value of the processingErrorCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode3() {
        return processingErrorCode3;
    }

    /**
     * Sets the value of the processingErrorCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode3(String value) {
        this.processingErrorCode3 = value;
    }

    /**
     * Gets the value of the processingErrorCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode4() {
        return processingErrorCode4;
    }

    /**
     * Sets the value of the processingErrorCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode4(String value) {
        this.processingErrorCode4 = value;
    }

    /**
     * Gets the value of the processingErrorCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode5() {
        return processingErrorCode5;
    }

    /**
     * Sets the value of the processingErrorCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode5(String value) {
        this.processingErrorCode5 = value;
    }

    /**
     * Gets the value of the processingErrorCode6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode6() {
        return processingErrorCode6;
    }

    /**
     * Sets the value of the processingErrorCode6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode6(String value) {
        this.processingErrorCode6 = value;
    }

    /**
     * Gets the value of the processingErrorCode7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode7() {
        return processingErrorCode7;
    }

    /**
     * Sets the value of the processingErrorCode7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode7(String value) {
        this.processingErrorCode7 = value;
    }

    /**
     * Gets the value of the processingErrorCode8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode8() {
        return processingErrorCode8;
    }

    /**
     * Sets the value of the processingErrorCode8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode8(String value) {
        this.processingErrorCode8 = value;
    }

    /**
     * Gets the value of the processingErrorCode9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorCode9() {
        return processingErrorCode9;
    }

    /**
     * Sets the value of the processingErrorCode9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorCode9(String value) {
        this.processingErrorCode9 = value;
    }

    /**
     * Gets the value of the fraudVictimIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudVictimIndicator() {
        return fraudVictimIndicator;
    }

    /**
     * Sets the value of the fraudVictimIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudVictimIndicator(String value) {
        this.fraudVictimIndicator = value;
    }

    /**
     * Gets the value of the safescanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafescanCode() {
        return safescanCode;
    }

    /**
     * Sets the value of the safescanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafescanCode(String value) {
        this.safescanCode = value;
    }

    /**
     * Gets the value of the cbiSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCbiSequenceNumber() {
        return cbiSequenceNumber;
    }

    /**
     * Sets the value of the cbiSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCbiSequenceNumber(String value) {
        this.cbiSequenceNumber = value;
    }

    /**
     * Gets the value of the acceptReject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptReject() {
        return acceptReject;
    }

    /**
     * Sets the value of the acceptReject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptReject(String value) {
        this.acceptReject = value;
    }

    /**
     * Gets the value of the acceptRejectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptRejectCode() {
        return acceptRejectCode;
    }

    /**
     * Sets the value of the acceptRejectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptRejectCode(String value) {
        this.acceptRejectCode = value;
    }

    /**
     * Gets the value of the pointScore1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointScore1() {
        return pointScore1;
    }

    /**
     * Sets the value of the pointScore1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointScore1(String value) {
        this.pointScore1 = value;
    }

    /**
     * Gets the value of the pointScore2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointScore2() {
        return pointScore2;
    }

    /**
     * Sets the value of the pointScore2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointScore2(String value) {
        this.pointScore2 = value;
    }

    /**
     * Gets the value of the locateNotice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocateNotice() {
        return locateNotice;
    }

    /**
     * Sets the value of the locateNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocateNotice(String value) {
        this.locateNotice = value;
    }

    /**
     * Gets the value of the manualFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualFile() {
        return manualFile;
    }

    /**
     * Sets the value of the manualFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualFile(String value) {
        this.manualFile = value;
    }

    /**
     * Gets the value of the underReview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderReview() {
        return underReview;
    }

    /**
     * Sets the value of the underReview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderReview(String value) {
        this.underReview = value;
    }

    /**
     * Gets the value of the consumerStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerStatement() {
        return consumerStatement;
    }

    /**
     * Sets the value of the consumerStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerStatement(String value) {
        this.consumerStatement = value;
    }

    /**
     * Gets the value of the noSolicitation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSolicitation() {
        return noSolicitation;
    }

    /**
     * Sets the value of the noSolicitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSolicitation(String value) {
        this.noSolicitation = value;
    }

    /**
     * Gets the value of the userReference2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReference2() {
        return userReference2;
    }

    /**
     * Sets the value of the userReference2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReference2(String value) {
        this.userReference2 = value;
    }

    /**
     * Gets the value of the addressDiscrepancyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressDiscrepancyIndicator() {
        return addressDiscrepancyIndicator;
    }

    /**
     * Sets the value of the addressDiscrepancyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressDiscrepancyIndicator(String value) {
        this.addressDiscrepancyIndicator = value;
    }

}
