//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.efu;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fico.afm.model.application.cdac.efu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fico.afm.model.application.cdac.efu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParsedResponseList }
     * 
     */
    public ParsedResponseList createParsedResponseList() {
        return new ParsedResponseList();
    }

    /**
     * Create an instance of {@link ParsedResponse }
     * 
     */
    public ParsedResponse createParsedResponse() {
        return new ParsedResponse();
    }

    /**
     * Create an instance of {@link HeaderList }
     * 
     */
    public HeaderList createHeaderList() {
        return new HeaderList();
    }

    /**
     * Create an instance of {@link HeaderEfu }
     * 
     */
    public HeaderEfu createHeaderEfu() {
        return new HeaderEfu();
    }

    /**
     * Create an instance of {@link IdentificationList }
     * 
     */
    public IdentificationList createIdentificationList() {
        return new IdentificationList();
    }

    /**
     * Create an instance of {@link IdentificationEfu }
     * 
     */
    public IdentificationEfu createIdentificationEfu() {
        return new IdentificationEfu();
    }

    /**
     * Create an instance of {@link NameOrAliasList }
     * 
     */
    public NameOrAliasList createNameOrAliasList() {
        return new NameOrAliasList();
    }

    /**
     * Create an instance of {@link NameOrAliasEfu }
     * 
     */
    public NameOrAliasEfu createNameOrAliasEfu() {
        return new NameOrAliasEfu();
    }

    /**
     * Create an instance of {@link AddressList }
     * 
     */
    public AddressList createAddressList() {
        return new AddressList();
    }

    /**
     * Create an instance of {@link AddressEfu }
     * 
     */
    public AddressEfu createAddressEfu() {
        return new AddressEfu();
    }

    /**
     * Create an instance of {@link EmploymentList }
     * 
     */
    public EmploymentList createEmploymentList() {
        return new EmploymentList();
    }

    /**
     * Create an instance of {@link EmploymentEfu }
     * 
     */
    public EmploymentEfu createEmploymentEfu() {
        return new EmploymentEfu();
    }

    /**
     * Create an instance of {@link ConsumerStatementList }
     * 
     */
    public ConsumerStatementList createConsumerStatementList() {
        return new ConsumerStatementList();
    }

    /**
     * Create an instance of {@link ConsumerStatementEfu }
     * 
     */
    public ConsumerStatementEfu createConsumerStatementEfu() {
        return new ConsumerStatementEfu();
    }

    /**
     * Create an instance of {@link PublicRecordList }
     * 
     */
    public PublicRecordList createPublicRecordList() {
        return new PublicRecordList();
    }

    /**
     * Create an instance of {@link PublicRecordEfu }
     * 
     */
    public PublicRecordEfu createPublicRecordEfu() {
        return new PublicRecordEfu();
    }

    /**
     * Create an instance of {@link CollectionList }
     * 
     */
    public CollectionList createCollectionList() {
        return new CollectionList();
    }

    /**
     * Create an instance of {@link CollectionEfu }
     * 
     */
    public CollectionEfu createCollectionEfu() {
        return new CollectionEfu();
    }

    /**
     * Create an instance of {@link TradelineList }
     * 
     */
    public TradelineList createTradelineList() {
        return new TradelineList();
    }

    /**
     * Create an instance of {@link TradelineEfu }
     * 
     */
    public TradelineEfu createTradelineEfu() {
        return new TradelineEfu();
    }

    /**
     * Create an instance of {@link InquiryList }
     * 
     */
    public InquiryList createInquiryList() {
        return new InquiryList();
    }

    /**
     * Create an instance of {@link InquiryEfu }
     * 
     */
    public InquiryEfu createInquiryEfu() {
        return new InquiryEfu();
    }

    /**
     * Create an instance of {@link BureauInformationList }
     * 
     */
    public BureauInformationList createBureauInformationList() {
        return new BureauInformationList();
    }

    /**
     * Create an instance of {@link BureauInformationEfu }
     * 
     */
    public BureauInformationEfu createBureauInformationEfu() {
        return new BureauInformationEfu();
    }

    /**
     * Create an instance of {@link ScoringList }
     * 
     */
    public ScoringList createScoringList() {
        return new ScoringList();
    }

    /**
     * Create an instance of {@link ScoringEfu }
     * 
     */
    public ScoringEfu createScoringEfu() {
        return new ScoringEfu();
    }

    /**
     * Create an instance of {@link FraudList }
     * 
     */
    public FraudList createFraudList() {
        return new FraudList();
    }

    /**
     * Create an instance of {@link FraudEfu }
     * 
     */
    public FraudEfu createFraudEfu() {
        return new FraudEfu();
    }

    /**
     * Create an instance of {@link DirectoryList }
     * 
     */
    public DirectoryList createDirectoryList() {
        return new DirectoryList();
    }

    /**
     * Create an instance of {@link DirectoryEfu }
     * 
     */
    public DirectoryEfu createDirectoryEfu() {
        return new DirectoryEfu();
    }

    /**
     * Create an instance of {@link SummaryInformationList }
     * 
     */
    public SummaryInformationList createSummaryInformationList() {
        return new SummaryInformationList();
    }

    /**
     * Create an instance of {@link SummaryInformationType }
     * 
     */
    public SummaryInformationType createSummaryInformationType() {
        return new SummaryInformationType();
    }

    /**
     * Create an instance of {@link PrintImageList }
     * 
     */
    public PrintImageList createPrintImageList() {
        return new PrintImageList();
    }

    /**
     * Create an instance of {@link PrintImageType }
     * 
     */
    public PrintImageType createPrintImageType() {
        return new PrintImageType();
    }

    /**
     * Create an instance of {@link MiscellaneousList }
     * 
     */
    public MiscellaneousList createMiscellaneousList() {
        return new MiscellaneousList();
    }

    /**
     * Create an instance of {@link MiscellaneousType }
     * 
     */
    public MiscellaneousType createMiscellaneousType() {
        return new MiscellaneousType();
    }

    /**
     * Create an instance of {@link EndSegmentList }
     * 
     */
    public EndSegmentList createEndSegmentList() {
        return new EndSegmentList();
    }

    /**
     * Create an instance of {@link EndSegmentType }
     * 
     */
    public EndSegmentType createEndSegmentType() {
        return new EndSegmentType();
    }

    /**
     * Create an instance of {@link CharacteristicList }
     * 
     */
    public CharacteristicList createCharacteristicList() {
        return new CharacteristicList();
    }

    /**
     * Create an instance of {@link Characteristic }
     * 
     */
    public Characteristic createCharacteristic() {
        return new Characteristic();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link NameOrAliasType }
     * 
     */
    public NameOrAliasType createNameOrAliasType() {
        return new NameOrAliasType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link EmploymentType }
     * 
     */
    public EmploymentType createEmploymentType() {
        return new EmploymentType();
    }

    /**
     * Create an instance of {@link ConsumerStatementType }
     * 
     */
    public ConsumerStatementType createConsumerStatementType() {
        return new ConsumerStatementType();
    }

    /**
     * Create an instance of {@link PublicRecordType }
     * 
     */
    public PublicRecordType createPublicRecordType() {
        return new PublicRecordType();
    }

    /**
     * Create an instance of {@link CollectionType }
     * 
     */
    public CollectionType createCollectionType() {
        return new CollectionType();
    }

    /**
     * Create an instance of {@link InquiryType }
     * 
     */
    public InquiryType createInquiryType() {
        return new InquiryType();
    }

    /**
     * Create an instance of {@link TradelineType }
     * 
     */
    public TradelineType createTradelineType() {
        return new TradelineType();
    }

    /**
     * Create an instance of {@link FraudType }
     * 
     */
    public FraudType createFraudType() {
        return new FraudType();
    }

    /**
     * Create an instance of {@link ScoringType }
     * 
     */
    public ScoringType createScoringType() {
        return new ScoringType();
    }

    /**
     * Create an instance of {@link DirectoryType }
     * 
     */
    public DirectoryType createDirectoryType() {
        return new DirectoryType();
    }

    /**
     * Create an instance of {@link BureauInformationType }
     * 
     */
    public BureauInformationType createBureauInformationType() {
        return new BureauInformationType();
    }

    /**
     * Create an instance of {@link EndSegmentXpn }
     * 
     */
    public EndSegmentXpn createEndSegmentXpn() {
        return new EndSegmentXpn();
    }

    /**
     * Create an instance of {@link UserDefined }
     * 
     */
    public UserDefined createUserDefined() {
        return new UserDefined();
    }

}
