//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.efu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * EFU 30, 31, 35 (DS, CP, MM) segments.
 * 
 * <p>Java class for ScoringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScoringType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute ref="{http://fico.com/dms/fidms/cc/cdac/efu}SourceSegment"/&gt;
 *       &lt;attribute name="Score" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ScoreSign" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FirstReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SecondReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ThirdReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FourthReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ModelTypeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoringType")
@XmlSeeAlso({
    ScoringEfu.class
})
public class ScoringType {

    @XmlAttribute(name = "SourceSegment", namespace = "http://fico.com/dms/fidms/cc/cdac/efu")
    protected String sourceSegment;
    @XmlAttribute(name = "Score")
    protected String score;
    @XmlAttribute(name = "ScoreSign")
    protected String scoreSign;
    @XmlAttribute(name = "FirstReasonCode")
    protected String firstReasonCode;
    @XmlAttribute(name = "SecondReasonCode")
    protected String secondReasonCode;
    @XmlAttribute(name = "ThirdReasonCode")
    protected String thirdReasonCode;
    @XmlAttribute(name = "FourthReasonCode")
    protected String fourthReasonCode;
    @XmlAttribute(name = "ModelTypeIndicator")
    protected String modelTypeIndicator;

    /**
     * EFU Source Segment
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSegment() {
        return sourceSegment;
    }

    /**
     * Sets the value of the sourceSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSegment(String value) {
        this.sourceSegment = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScore(String value) {
        this.score = value;
    }

    /**
     * Gets the value of the scoreSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreSign() {
        return scoreSign;
    }

    /**
     * Sets the value of the scoreSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreSign(String value) {
        this.scoreSign = value;
    }

    /**
     * Gets the value of the firstReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstReasonCode() {
        return firstReasonCode;
    }

    /**
     * Sets the value of the firstReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstReasonCode(String value) {
        this.firstReasonCode = value;
    }

    /**
     * Gets the value of the secondReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondReasonCode() {
        return secondReasonCode;
    }

    /**
     * Sets the value of the secondReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondReasonCode(String value) {
        this.secondReasonCode = value;
    }

    /**
     * Gets the value of the thirdReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdReasonCode() {
        return thirdReasonCode;
    }

    /**
     * Sets the value of the thirdReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdReasonCode(String value) {
        this.thirdReasonCode = value;
    }

    /**
     * Gets the value of the fourthReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFourthReasonCode() {
        return fourthReasonCode;
    }

    /**
     * Sets the value of the fourthReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFourthReasonCode(String value) {
        this.fourthReasonCode = value;
    }

    /**
     * Gets the value of the modelTypeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelTypeIndicator() {
        return modelTypeIndicator;
    }

    /**
     * Sets the value of the modelTypeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelTypeIndicator(String value) {
        this.modelTypeIndicator = value;
    }

}
