/*
 *  AI Fraud Prediction API.
 * Clients can submit customer data to the machine learning model and get a prediction back. ( the AI is trained to perform fraud prediction) . 
 *
 * OpenAPI spec version: 1.0
 * Contact: dlCSOInnovation@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.telus.subsfraudmgmt.api.model.watson;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PredictionPredictions
 */

public class PredictionPredictions {
  @JsonProperty("fields")
  private List<String> fields = null;

  @JsonProperty("values")
  private List<Object> values = null;

  public PredictionPredictions fields(List<String> fields) {
    this.fields = fields;
    return this;
  }

  public PredictionPredictions addFieldsItem(String fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<String>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(value = "")
  public List<String> getFields() {
    return fields;
  }

  public void setFields(List<String> fields) {
    this.fields = fields;
  }

  public PredictionPredictions values(List<Object> values) {
    this.values = values;
    return this;
  }

  public PredictionPredictions addValuesItem(Object valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<Object>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(value = "")
  public List<Object> getValues() {
    return values;
  }

  public void setValues(List<Object> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionPredictions predictionPredictions = (PredictionPredictions) o;
    return Objects.equals(this.fields, predictionPredictions.fields) &&
        Objects.equals(this.values, predictionPredictions.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionPredictions {\n");
    
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

