//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.types;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.fico.afm.model.application.AbstractRule;
import com.fico.afm.model.application.CaseHistory;
import com.fico.afm.model.application.Disposition;
import com.fico.afm.model.application.Phone;
import org.w3._2001.xmlschema.Adapter1;


/**
 * This is the base object definition for any object that supports custom extensions by
 *                 customers. Objects can be extended with simple name-value pairs, or, with a little more effort, whole
 *                 custom objects.
 *             
 * 
 * <p>Java class for AbstractExtensibleObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractExtensibleObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.fico.com/fraud/schemas/types}AbstractEntity"/&gt;
 *         &lt;element name="userData" type="{http://www.fico.com/fraud/schemas/types}AliasableNameValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractExtensibleObject", propOrder = {
    "entityCreateDate",
    "entityLastUpdateDate",
    "id",
    "version",
    "userData"
})
@XmlSeeAlso({
    AbstractRule.class,
    CaseHistory.class,
    Disposition.class,
    Phone.class
})
public abstract class AbstractExtensibleObject {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar entityCreateDate;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar entityLastUpdateDate;
    protected BigInteger id;
    protected Integer version;
    protected List<AliasableNameValuePair> userData;

    /**
     * Gets the value of the entityCreateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getEntityCreateDate() {
        return entityCreateDate;
    }

    /**
     * Sets the value of the entityCreateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityCreateDate(Calendar value) {
        this.entityCreateDate = value;
    }

    /**
     * Gets the value of the entityLastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getEntityLastUpdateDate() {
        return entityLastUpdateDate;
    }

    /**
     * Sets the value of the entityLastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityLastUpdateDate(Calendar value) {
        this.entityLastUpdateDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AliasableNameValuePair }
     * 
     * 
     */
    public List<AliasableNameValuePair> getUserData() {
        if (userData == null) {
            userData = new ArrayList<AliasableNameValuePair>();
        }
        return this.userData;
    }

}
