//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MortgageProductType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MortgageProductType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FIXED"/&gt;
 *     &lt;enumeration value="DISCOUNTED_RATE"/&gt;
 *     &lt;enumeration value="TRACKER"/&gt;
 *     &lt;enumeration value="OFFSET"/&gt;
 *     &lt;enumeration value="CAPPED"/&gt;
 *     &lt;enumeration value="STANDARD_VARIABLE"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MortgageProductType")
@XmlEnum
public enum MortgageProductType {

    FIXED,
    DISCOUNTED_RATE,
    TRACKER,
    OFFSET,
    CAPPED,
    STANDARD_VARIABLE,
    OTHER;

    public String value() {
        return name();
    }

    public static MortgageProductType fromValue(String v) {
        return valueOf(v);
    }

}
