//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchConditionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SearchConditionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Application"/&gt;
 *     &lt;enumeration value="BureauReport"/&gt;
 *     &lt;enumeration value="Blacklist"/&gt;
 *     &lt;enumeration value="Hotlist"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SearchConditionType")
@XmlEnum
public enum SearchConditionType {

    @XmlEnumValue("Application")
    APPLICATION("Application"),
    @XmlEnumValue("BureauReport")
    BUREAU_REPORT("BureauReport"),
    @XmlEnumValue("Blacklist")
    BLACKLIST("Blacklist"),
    @XmlEnumValue("Hotlist")
    HOTLIST("Hotlist");
    private final String value;

    SearchConditionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SearchConditionType fromValue(String v) {
        for (SearchConditionType c: SearchConditionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
