//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.fico.afm.model.application.types.AbstractExtensibleObject;
import com.fico.afm.model.application.types.AddressResidenceType;
import org.w3._2001.xmlschema.Adapter2;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fico.com/fraud/schemas/types}AbstractExtensibleObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="street1" type="{http://www.fico.com/fraud/schemas/types}String150"/&gt;
 *         &lt;element name="street2" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="street3" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="street4" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="street5" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="street6" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="street7" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="city" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="stateOrProvince" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="postalCode" type="{http://www.fico.com/fraud/schemas/types}String16"/&gt;
 *         &lt;element name="county" type="{http://www.fico.com/fraud/schemas/types}String150" minOccurs="0"/&gt;
 *         &lt;element name="countryCode" type="{http://www.fico.com/fraud/schemas/types}String16"/&gt;
 *         &lt;element name="addressResidenceType" type="{http://www.fico.com/fraud/schemas/types}AddressResidenceType" minOccurs="0"/&gt;
 *         &lt;element name="fromDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="toDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="label" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="current" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "street1",
    "street2",
    "street3",
    "street4",
    "street5",
    "street6",
    "street7",
    "city",
    "stateOrProvince",
    "postalCode",
    "county",
    "countryCode",
    "addressResidenceType",
    "fromDate",
    "toDate",
    "label"
})
public class Address
    extends AbstractExtensibleObject
{

    @XmlElement(required = true)
    protected String street1;
    protected String street2;
    protected String street3;
    protected String street4;
    protected String street5;
    protected String street6;
    protected String street7;
    @XmlElement(required = true)
    protected String city;
    protected String stateOrProvince;
    @XmlElement(required = true)
    protected String postalCode;
    protected String county;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlSchemaType(name = "string")
    protected AddressResidenceType addressResidenceType;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar fromDate;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar toDate;
    protected String label;
    @XmlAttribute(name = "current")
    protected Boolean current;

    /**
     * Gets the value of the street1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet1() {
        return street1;
    }

    /**
     * Sets the value of the street1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet1(String value) {
        this.street1 = value;
    }

    /**
     * Gets the value of the street2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet2() {
        return street2;
    }

    /**
     * Sets the value of the street2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet2(String value) {
        this.street2 = value;
    }

    /**
     * Gets the value of the street3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet3() {
        return street3;
    }

    /**
     * Sets the value of the street3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet3(String value) {
        this.street3 = value;
    }

    /**
     * Gets the value of the street4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet4() {
        return street4;
    }

    /**
     * Sets the value of the street4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet4(String value) {
        this.street4 = value;
    }

    /**
     * Gets the value of the street5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet5() {
        return street5;
    }

    /**
     * Sets the value of the street5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet5(String value) {
        this.street5 = value;
    }

    /**
     * Gets the value of the street6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet6() {
        return street6;
    }

    /**
     * Sets the value of the street6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet6(String value) {
        this.street6 = value;
    }

    /**
     * Gets the value of the street7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet7() {
        return street7;
    }

    /**
     * Sets the value of the street7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet7(String value) {
        this.street7 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateOrProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateOrProvince() {
        return stateOrProvince;
    }

    /**
     * Sets the value of the stateOrProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateOrProvince(String value) {
        this.stateOrProvince = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the addressResidenceType property.
     * 
     * @return
     *     possible object is
     *     {@link AddressResidenceType }
     *     
     */
    public AddressResidenceType getAddressResidenceType() {
        return addressResidenceType;
    }

    /**
     * Sets the value of the addressResidenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressResidenceType }
     *     
     */
    public void setAddressResidenceType(AddressResidenceType value) {
        this.addressResidenceType = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(Calendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(Calendar value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrent(Boolean value) {
        this.current = value;
    }

}
