//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import com.fico.afm.model.application.types.AbstractExtensibleObject;


/**
 * <p>Java class for ApplicationSectionCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationSectionCard"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fico.com/fraud/schemas/types}AbstractExtensibleObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requestedCreditLimit" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="cardType" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="requestedInterestRate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="dealInterestRate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="dealTerm" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="finalCreditLimit" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="finalInterestRate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="campaignResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationSectionCard", propOrder = {
    "requestedCreditLimit",
    "cardType",
    "requestedInterestRate",
    "dealInterestRate",
    "dealTerm",
    "finalCreditLimit",
    "finalInterestRate"
})
public class ApplicationSectionCard
    extends AbstractExtensibleObject
{

    protected BigDecimal requestedCreditLimit;
    protected String cardType;
    protected Float requestedInterestRate;
    protected Float dealInterestRate;
    protected Short dealTerm;
    protected BigDecimal finalCreditLimit;
    protected Float finalInterestRate;
    @XmlAttribute(name = "campaignResponse")
    protected Boolean campaignResponse;

    /**
     * Gets the value of the requestedCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestedCreditLimit() {
        return requestedCreditLimit;
    }

    /**
     * Sets the value of the requestedCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestedCreditLimit(BigDecimal value) {
        this.requestedCreditLimit = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the requestedInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRequestedInterestRate() {
        return requestedInterestRate;
    }

    /**
     * Sets the value of the requestedInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRequestedInterestRate(Float value) {
        this.requestedInterestRate = value;
    }

    /**
     * Gets the value of the dealInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDealInterestRate() {
        return dealInterestRate;
    }

    /**
     * Sets the value of the dealInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDealInterestRate(Float value) {
        this.dealInterestRate = value;
    }

    /**
     * Gets the value of the dealTerm property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDealTerm() {
        return dealTerm;
    }

    /**
     * Sets the value of the dealTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDealTerm(Short value) {
        this.dealTerm = value;
    }

    /**
     * Gets the value of the finalCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalCreditLimit() {
        return finalCreditLimit;
    }

    /**
     * Sets the value of the finalCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalCreditLimit(BigDecimal value) {
        this.finalCreditLimit = value;
    }

    /**
     * Gets the value of the finalInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFinalInterestRate() {
        return finalInterestRate;
    }

    /**
     * Sets the value of the finalInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFinalInterestRate(Float value) {
        this.finalInterestRate = value;
    }

    /**
     * Gets the value of the campaignResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCampaignResponse() {
        return campaignResponse;
    }

    /**
     * Sets the value of the campaignResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCampaignResponse(Boolean value) {
        this.campaignResponse = value;
    }

}
