//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.fico.afm.model.application.types.AbstractExtensibleObject;
import com.fico.afm.model.application.types.AutoTransferInitiatedType;
import com.fico.afm.model.application.types.DealerStatusType;
import com.fico.afm.model.application.types.VehicleNewUsedIndicatorType;
import com.fico.afm.model.application.types.VehicleUsedValueGuideType;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for ApplicationSectionAuto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationSectionAuto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fico.com/fraud/schemas/types}AbstractExtensibleObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dealTerm" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="monthlyFee" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="vehicleId" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="vehicleTotalPurchasePrice" type="{http://www.fico.com/fraud/schemas/types}Currency"/&gt;
 *         &lt;element name="vehicleNameOnTitle" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="vehicleMake" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="vehicleMakeRegion" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="vehicleModel" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="vehicleYear" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="vehicleNewUsedIndicator" type="{http://www.fico.com/fraud/schemas/types}VehicleNewUsedIndicatorType"/&gt;
 *         &lt;element name="vehicleUsedValueGuide" type="{http://www.fico.com/fraud/schemas/types}VehicleUsedValueGuideType"/&gt;
 *         &lt;element name="vehicleBookValue" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="vehicleEngineType" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="vehicleEngineSize" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="vehicleSerialOrVinNum" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="vehicleMileage" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="vehicleLuxuryIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="dealerId" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="dealerName" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="dealerSize" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="address" type="{http://www.fico.com/fraud/schemas}Address" maxOccurs="unbounded"/&gt;
 *         &lt;element name="phone" type="{http://www.fico.com/fraud/schemas}Phone" maxOccurs="unbounded"/&gt;
 *         &lt;element name="dealerStatus" type="{http://www.fico.com/fraud/schemas/types}DealerStatusType" minOccurs="0"/&gt;
 *         &lt;element name="dealerType" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="dealerIncentivePlan" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="dealerTotalApps" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="dealerCaptureRate" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="dealerAssociateId" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="dealerAssociateName" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="dealerAssociateRole" type="{http://www.fico.com/fraud/schemas/types}String32"/&gt;
 *         &lt;element name="dealerAssociateCaptureRate" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="autoWarranty" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="autoWarrantyTerm" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="autoWarrantyCost" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="autoModelPackage" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="autoDealerOption" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="autoFinanceCompany" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="autoCommission" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="autoFinanceManager" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="autoDealerManager" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="autoTransfer" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="autoTransferDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="autoTransferInitiated" type="{http://www.fico.com/fraud/schemas/types}AutoTransferInitiatedType" minOccurs="0"/&gt;
 *         &lt;element name="autoTransferDeposit" type="{http://www.fico.com/fraud/schemas/types}Currency" minOccurs="0"/&gt;
 *         &lt;element name="autoTestDrive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="autoTestDriveIdentificationDocumentation" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationSectionAuto", propOrder = {
    "dealTerm",
    "monthlyFee",
    "vehicleId",
    "vehicleTotalPurchasePrice",
    "vehicleNameOnTitle",
    "vehicleMake",
    "vehicleMakeRegion",
    "vehicleModel",
    "vehicleYear",
    "vehicleNewUsedIndicator",
    "vehicleUsedValueGuide",
    "vehicleBookValue",
    "vehicleEngineType",
    "vehicleEngineSize",
    "vehicleSerialOrVinNum",
    "vehicleMileage",
    "vehicleLuxuryIndicator",
    "dealerId",
    "dealerName",
    "dealerSize",
    "address",
    "phone",
    "dealerStatus",
    "dealerType",
    "dealerIncentivePlan",
    "dealerTotalApps",
    "dealerCaptureRate",
    "dealerAssociateId",
    "dealerAssociateName",
    "dealerAssociateRole",
    "dealerAssociateCaptureRate",
    "autoWarranty",
    "autoWarrantyTerm",
    "autoWarrantyCost",
    "autoModelPackage",
    "autoDealerOption",
    "autoFinanceCompany",
    "autoCommission",
    "autoFinanceManager",
    "autoDealerManager",
    "autoTransfer",
    "autoTransferDate",
    "autoTransferInitiated",
    "autoTransferDeposit",
    "autoTestDrive",
    "autoTestDriveIdentificationDocumentation"
})
public class ApplicationSectionAuto
    extends AbstractExtensibleObject
{

    protected Short dealTerm;
    protected BigDecimal monthlyFee;
    @XmlElement(required = true)
    protected String vehicleId;
    @XmlElement(required = true)
    protected BigDecimal vehicleTotalPurchasePrice;
    protected String vehicleNameOnTitle;
    @XmlElement(required = true)
    protected String vehicleMake;
    protected String vehicleMakeRegion;
    @XmlElement(required = true)
    protected String vehicleModel;
    protected short vehicleYear;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VehicleNewUsedIndicatorType vehicleNewUsedIndicator;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VehicleUsedValueGuideType vehicleUsedValueGuide;
    protected BigDecimal vehicleBookValue;
    protected String vehicleEngineType;
    protected BigInteger vehicleEngineSize;
    @XmlElement(required = true)
    protected String vehicleSerialOrVinNum;
    @XmlElement(required = true)
    protected BigInteger vehicleMileage;
    protected Boolean vehicleLuxuryIndicator;
    @XmlElement(required = true)
    protected String dealerId;
    @XmlElement(required = true)
    protected String dealerName;
    @XmlElement(required = true)
    protected BigInteger dealerSize;
    @XmlElement(required = true)
    protected List<Address> address;
    @XmlElement(required = true)
    protected List<Phone> phone;
    @XmlSchemaType(name = "string")
    protected DealerStatusType dealerStatus;
    protected String dealerType;
    protected String dealerIncentivePlan;
    @XmlElement(required = true)
    protected BigInteger dealerTotalApps;
    protected float dealerCaptureRate;
    @XmlElement(required = true)
    protected String dealerAssociateId;
    @XmlElement(required = true)
    protected String dealerAssociateName;
    @XmlElement(required = true)
    protected String dealerAssociateRole;
    protected float dealerAssociateCaptureRate;
    protected String autoWarranty;
    protected Short autoWarrantyTerm;
    protected BigDecimal autoWarrantyCost;
    protected String autoModelPackage;
    protected String autoDealerOption;
    protected String autoFinanceCompany;
    protected BigDecimal autoCommission;
    protected String autoFinanceManager;
    protected String autoDealerManager;
    protected String autoTransfer;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar autoTransferDate;
    @XmlSchemaType(name = "string")
    protected AutoTransferInitiatedType autoTransferInitiated;
    protected BigDecimal autoTransferDeposit;
    protected Boolean autoTestDrive;
    protected String autoTestDriveIdentificationDocumentation;

    /**
     * Gets the value of the dealTerm property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDealTerm() {
        return dealTerm;
    }

    /**
     * Sets the value of the dealTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDealTerm(Short value) {
        this.dealTerm = value;
    }

    /**
     * Gets the value of the monthlyFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyFee() {
        return monthlyFee;
    }

    /**
     * Sets the value of the monthlyFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyFee(BigDecimal value) {
        this.monthlyFee = value;
    }

    /**
     * Gets the value of the vehicleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * Sets the value of the vehicleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleId(String value) {
        this.vehicleId = value;
    }

    /**
     * Gets the value of the vehicleTotalPurchasePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVehicleTotalPurchasePrice() {
        return vehicleTotalPurchasePrice;
    }

    /**
     * Sets the value of the vehicleTotalPurchasePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVehicleTotalPurchasePrice(BigDecimal value) {
        this.vehicleTotalPurchasePrice = value;
    }

    /**
     * Gets the value of the vehicleNameOnTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleNameOnTitle() {
        return vehicleNameOnTitle;
    }

    /**
     * Sets the value of the vehicleNameOnTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleNameOnTitle(String value) {
        this.vehicleNameOnTitle = value;
    }

    /**
     * Gets the value of the vehicleMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMake() {
        return vehicleMake;
    }

    /**
     * Sets the value of the vehicleMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMake(String value) {
        this.vehicleMake = value;
    }

    /**
     * Gets the value of the vehicleMakeRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMakeRegion() {
        return vehicleMakeRegion;
    }

    /**
     * Sets the value of the vehicleMakeRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMakeRegion(String value) {
        this.vehicleMakeRegion = value;
    }

    /**
     * Gets the value of the vehicleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * Sets the value of the vehicleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleModel(String value) {
        this.vehicleModel = value;
    }

    /**
     * Gets the value of the vehicleYear property.
     * 
     */
    public short getVehicleYear() {
        return vehicleYear;
    }

    /**
     * Sets the value of the vehicleYear property.
     * 
     */
    public void setVehicleYear(short value) {
        this.vehicleYear = value;
    }

    /**
     * Gets the value of the vehicleNewUsedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleNewUsedIndicatorType }
     *     
     */
    public VehicleNewUsedIndicatorType getVehicleNewUsedIndicator() {
        return vehicleNewUsedIndicator;
    }

    /**
     * Sets the value of the vehicleNewUsedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleNewUsedIndicatorType }
     *     
     */
    public void setVehicleNewUsedIndicator(VehicleNewUsedIndicatorType value) {
        this.vehicleNewUsedIndicator = value;
    }

    /**
     * Gets the value of the vehicleUsedValueGuide property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleUsedValueGuideType }
     *     
     */
    public VehicleUsedValueGuideType getVehicleUsedValueGuide() {
        return vehicleUsedValueGuide;
    }

    /**
     * Sets the value of the vehicleUsedValueGuide property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleUsedValueGuideType }
     *     
     */
    public void setVehicleUsedValueGuide(VehicleUsedValueGuideType value) {
        this.vehicleUsedValueGuide = value;
    }

    /**
     * Gets the value of the vehicleBookValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVehicleBookValue() {
        return vehicleBookValue;
    }

    /**
     * Sets the value of the vehicleBookValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVehicleBookValue(BigDecimal value) {
        this.vehicleBookValue = value;
    }

    /**
     * Gets the value of the vehicleEngineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleEngineType() {
        return vehicleEngineType;
    }

    /**
     * Sets the value of the vehicleEngineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleEngineType(String value) {
        this.vehicleEngineType = value;
    }

    /**
     * Gets the value of the vehicleEngineSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVehicleEngineSize() {
        return vehicleEngineSize;
    }

    /**
     * Sets the value of the vehicleEngineSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVehicleEngineSize(BigInteger value) {
        this.vehicleEngineSize = value;
    }

    /**
     * Gets the value of the vehicleSerialOrVinNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleSerialOrVinNum() {
        return vehicleSerialOrVinNum;
    }

    /**
     * Sets the value of the vehicleSerialOrVinNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleSerialOrVinNum(String value) {
        this.vehicleSerialOrVinNum = value;
    }

    /**
     * Gets the value of the vehicleMileage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVehicleMileage() {
        return vehicleMileage;
    }

    /**
     * Sets the value of the vehicleMileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVehicleMileage(BigInteger value) {
        this.vehicleMileage = value;
    }

    /**
     * Gets the value of the vehicleLuxuryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getVehicleLuxuryIndicator() {
        return vehicleLuxuryIndicator;
    }

    /**
     * Sets the value of the vehicleLuxuryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVehicleLuxuryIndicator(Boolean value) {
        this.vehicleLuxuryIndicator = value;
    }

    /**
     * Gets the value of the dealerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * Sets the value of the dealerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerId(String value) {
        this.dealerId = value;
    }

    /**
     * Gets the value of the dealerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * Sets the value of the dealerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerName(String value) {
        this.dealerName = value;
    }

    /**
     * Gets the value of the dealerSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDealerSize() {
        return dealerSize;
    }

    /**
     * Sets the value of the dealerSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDealerSize(BigInteger value) {
        this.dealerSize = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Phone }
     * 
     * 
     */
    public List<Phone> getPhone() {
        if (phone == null) {
            phone = new ArrayList<Phone>();
        }
        return this.phone;
    }

    /**
     * Gets the value of the dealerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DealerStatusType }
     *     
     */
    public DealerStatusType getDealerStatus() {
        return dealerStatus;
    }

    /**
     * Sets the value of the dealerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealerStatusType }
     *     
     */
    public void setDealerStatus(DealerStatusType value) {
        this.dealerStatus = value;
    }

    /**
     * Gets the value of the dealerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerType() {
        return dealerType;
    }

    /**
     * Sets the value of the dealerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerType(String value) {
        this.dealerType = value;
    }

    /**
     * Gets the value of the dealerIncentivePlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerIncentivePlan() {
        return dealerIncentivePlan;
    }

    /**
     * Sets the value of the dealerIncentivePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerIncentivePlan(String value) {
        this.dealerIncentivePlan = value;
    }

    /**
     * Gets the value of the dealerTotalApps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDealerTotalApps() {
        return dealerTotalApps;
    }

    /**
     * Sets the value of the dealerTotalApps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDealerTotalApps(BigInteger value) {
        this.dealerTotalApps = value;
    }

    /**
     * Gets the value of the dealerCaptureRate property.
     * 
     */
    public float getDealerCaptureRate() {
        return dealerCaptureRate;
    }

    /**
     * Sets the value of the dealerCaptureRate property.
     * 
     */
    public void setDealerCaptureRate(float value) {
        this.dealerCaptureRate = value;
    }

    /**
     * Gets the value of the dealerAssociateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerAssociateId() {
        return dealerAssociateId;
    }

    /**
     * Sets the value of the dealerAssociateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerAssociateId(String value) {
        this.dealerAssociateId = value;
    }

    /**
     * Gets the value of the dealerAssociateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerAssociateName() {
        return dealerAssociateName;
    }

    /**
     * Sets the value of the dealerAssociateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerAssociateName(String value) {
        this.dealerAssociateName = value;
    }

    /**
     * Gets the value of the dealerAssociateRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerAssociateRole() {
        return dealerAssociateRole;
    }

    /**
     * Sets the value of the dealerAssociateRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerAssociateRole(String value) {
        this.dealerAssociateRole = value;
    }

    /**
     * Gets the value of the dealerAssociateCaptureRate property.
     * 
     */
    public float getDealerAssociateCaptureRate() {
        return dealerAssociateCaptureRate;
    }

    /**
     * Sets the value of the dealerAssociateCaptureRate property.
     * 
     */
    public void setDealerAssociateCaptureRate(float value) {
        this.dealerAssociateCaptureRate = value;
    }

    /**
     * Gets the value of the autoWarranty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoWarranty() {
        return autoWarranty;
    }

    /**
     * Sets the value of the autoWarranty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoWarranty(String value) {
        this.autoWarranty = value;
    }

    /**
     * Gets the value of the autoWarrantyTerm property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAutoWarrantyTerm() {
        return autoWarrantyTerm;
    }

    /**
     * Sets the value of the autoWarrantyTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAutoWarrantyTerm(Short value) {
        this.autoWarrantyTerm = value;
    }

    /**
     * Gets the value of the autoWarrantyCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAutoWarrantyCost() {
        return autoWarrantyCost;
    }

    /**
     * Sets the value of the autoWarrantyCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAutoWarrantyCost(BigDecimal value) {
        this.autoWarrantyCost = value;
    }

    /**
     * Gets the value of the autoModelPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoModelPackage() {
        return autoModelPackage;
    }

    /**
     * Sets the value of the autoModelPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoModelPackage(String value) {
        this.autoModelPackage = value;
    }

    /**
     * Gets the value of the autoDealerOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoDealerOption() {
        return autoDealerOption;
    }

    /**
     * Sets the value of the autoDealerOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoDealerOption(String value) {
        this.autoDealerOption = value;
    }

    /**
     * Gets the value of the autoFinanceCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoFinanceCompany() {
        return autoFinanceCompany;
    }

    /**
     * Sets the value of the autoFinanceCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoFinanceCompany(String value) {
        this.autoFinanceCompany = value;
    }

    /**
     * Gets the value of the autoCommission property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAutoCommission() {
        return autoCommission;
    }

    /**
     * Sets the value of the autoCommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAutoCommission(BigDecimal value) {
        this.autoCommission = value;
    }

    /**
     * Gets the value of the autoFinanceManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoFinanceManager() {
        return autoFinanceManager;
    }

    /**
     * Sets the value of the autoFinanceManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoFinanceManager(String value) {
        this.autoFinanceManager = value;
    }

    /**
     * Gets the value of the autoDealerManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoDealerManager() {
        return autoDealerManager;
    }

    /**
     * Sets the value of the autoDealerManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoDealerManager(String value) {
        this.autoDealerManager = value;
    }

    /**
     * Gets the value of the autoTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoTransfer() {
        return autoTransfer;
    }

    /**
     * Sets the value of the autoTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoTransfer(String value) {
        this.autoTransfer = value;
    }

    /**
     * Gets the value of the autoTransferDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getAutoTransferDate() {
        return autoTransferDate;
    }

    /**
     * Sets the value of the autoTransferDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoTransferDate(Calendar value) {
        this.autoTransferDate = value;
    }

    /**
     * Gets the value of the autoTransferInitiated property.
     * 
     * @return
     *     possible object is
     *     {@link AutoTransferInitiatedType }
     *     
     */
    public AutoTransferInitiatedType getAutoTransferInitiated() {
        return autoTransferInitiated;
    }

    /**
     * Sets the value of the autoTransferInitiated property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoTransferInitiatedType }
     *     
     */
    public void setAutoTransferInitiated(AutoTransferInitiatedType value) {
        this.autoTransferInitiated = value;
    }

    /**
     * Gets the value of the autoTransferDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAutoTransferDeposit() {
        return autoTransferDeposit;
    }

    /**
     * Sets the value of the autoTransferDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAutoTransferDeposit(BigDecimal value) {
        this.autoTransferDeposit = value;
    }

    /**
     * Gets the value of the autoTestDrive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoTestDrive() {
        return autoTestDrive;
    }

    /**
     * Sets the value of the autoTestDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoTestDrive(Boolean value) {
        this.autoTestDrive = value;
    }

    /**
     * Gets the value of the autoTestDriveIdentificationDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoTestDriveIdentificationDocumentation() {
        return autoTestDriveIdentificationDocumentation;
    }

    /**
     * Sets the value of the autoTestDriveIdentificationDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoTestDriveIdentificationDocumentation(String value) {
        this.autoTestDriveIdentificationDocumentation = value;
    }

}
