//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BureauReportType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BureauReportType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Experian"/&gt;
 *     &lt;enumeration value="TransUnion"/&gt;
 *     &lt;enumeration value="Equifax"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "BureauReportType")
@XmlEnum
public enum BureauReportType {

    @XmlEnumValue("Experian")
    EXPERIAN("Experian"),
    @XmlEnumValue("TransUnion")
    TRANS_UNION("TransUnion"),
    @XmlEnumValue("Equifax")
    EQUIFAX("Equifax"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    BureauReportType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BureauReportType fromValue(String v) {
        for (BureauReportType c: BureauReportType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
