//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import java.math.BigInteger;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * 
 *                 Base object for BureauReport so that we can derive bureau specific
 *                 (Equifax, Experian, TransUnion
 *                 variants).
 *             
 * 
 * <p>Java class for BureauReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BureauReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.fico.com/fraud/schemas/types}AbstractEntity"/&gt;
 *         &lt;element name="identificationNumber" type="{http://www.fico.com/fraud/schemas/types}String32" minOccurs="0"/&gt;
 *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.fico.com/fraud/schemas}BureauReportType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BureauReport", propOrder = {
    "entityCreateDate",
    "entityLastUpdateDate",
    "id",
    "version",
    "identificationNumber",
    "report",
    "type"
})
@XmlSeeAlso({
    EfuBureauReport.class,
    TuBureauReport.class,
    XpnBureauReport.class,
    OtherBureauReport.class
})
public abstract class BureauReport {

    @XmlElement(namespace = "http://www.fico.com/fraud/schemas/types", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar entityCreateDate;
    @XmlElement(namespace = "http://www.fico.com/fraud/schemas/types", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar entityLastUpdateDate;
    @XmlElement(namespace = "http://www.fico.com/fraud/schemas/types")
    protected BigInteger id;
    @XmlElement(namespace = "http://www.fico.com/fraud/schemas/types")
    protected Integer version;
    protected String identificationNumber;
    protected Object report;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BureauReportType type;

    /**
     * Gets the value of the entityCreateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getEntityCreateDate() {
        return entityCreateDate;
    }

    /**
     * Sets the value of the entityCreateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityCreateDate(Calendar value) {
        this.entityCreateDate = value;
    }

    /**
     * Gets the value of the entityLastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getEntityLastUpdateDate() {
        return entityLastUpdateDate;
    }

    /**
     * Sets the value of the entityLastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityLastUpdateDate(Calendar value) {
        this.entityLastUpdateDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }

    /**
     * Gets the value of the identificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * Sets the value of the identificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationNumber(String value) {
        this.identificationNumber = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReport(Object value) {
        this.report = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BureauReportType }
     *     
     */
    public BureauReportType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BureauReportType }
     *     
     */
    public void setType(BureauReportType value) {
        this.type = value;
    }

}
