//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.fico.afm.model.application.types.AbstractExtensibleObject;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for CaseHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseHistory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fico.com/fraud/schemas/types}AbstractExtensibleObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="actionType" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="actionPerformedBy" type="{http://www.fico.com/fraud/schemas/types}String128"/&gt;
 *         &lt;element name="actionDetails" type="{http://www.fico.com/fraud/schemas/types}String256"/&gt;
 *         &lt;element name="status" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="fraudDisposition" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="fraudType" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="judgementSource" type="{http://www.fico.com/fraud/schemas/types}String64"/&gt;
 *         &lt;element name="comments" type="{http://www.fico.com/fraud/schemas/types}String512" minOccurs="0"/&gt;
 *         &lt;element name="applicationId" type="{http://www.fico.com/fraud/schemas/types}String64" minOccurs="0"/&gt;
 *         &lt;element name="caseId" type="{http://www.fico.com/fraud/schemas/types}String8" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseHistory", propOrder = {
    "actionDateTime",
    "actionType",
    "actionPerformedBy",
    "actionDetails",
    "status",
    "fraudDisposition",
    "fraudType",
    "judgementSource",
    "comments",
    "applicationId",
    "caseId"
})
public class CaseHistory
    extends AbstractExtensibleObject
{

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar actionDateTime;
    @XmlElement(required = true)
    protected String actionType;
    @XmlElement(required = true)
    protected String actionPerformedBy;
    @XmlElement(required = true)
    protected String actionDetails;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String fraudDisposition;
    @XmlElement(required = true)
    protected String fraudType;
    @XmlElement(required = true)
    protected String judgementSource;
    protected String comments;
    protected String applicationId;
    protected String caseId;

    /**
     * Gets the value of the actionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getActionDateTime() {
        return actionDateTime;
    }

    /**
     * Sets the value of the actionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionDateTime(Calendar value) {
        this.actionDateTime = value;
    }

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the actionPerformedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionPerformedBy() {
        return actionPerformedBy;
    }

    /**
     * Sets the value of the actionPerformedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionPerformedBy(String value) {
        this.actionPerformedBy = value;
    }

    /**
     * Gets the value of the actionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionDetails() {
        return actionDetails;
    }

    /**
     * Sets the value of the actionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionDetails(String value) {
        this.actionDetails = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the fraudDisposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudDisposition() {
        return fraudDisposition;
    }

    /**
     * Sets the value of the fraudDisposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudDisposition(String value) {
        this.fraudDisposition = value;
    }

    /**
     * Gets the value of the fraudType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudType() {
        return fraudType;
    }

    /**
     * Sets the value of the fraudType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudType(String value) {
        this.fraudType = value;
    }

    /**
     * Gets the value of the judgementSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJudgementSource() {
        return judgementSource;
    }

    /**
     * Sets the value of the judgementSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJudgementSource(String value) {
        this.judgementSource = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the applicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets the value of the applicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationId(String value) {
        this.applicationId = value;
    }

    /**
     * Gets the value of the caseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

}
