//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fico.afm.model.application package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Case_QNAME = new QName("http://www.fico.com/fraud/schemas", "Case");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fico.afm.model.application
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaseType }
     * 
     */
    public CaseType createCaseType() {
        return new CaseType();
    }

    /**
     * Create an instance of {@link Cases }
     * 
     */
    public Cases createCases() {
        return new Cases();
    }

    /**
     * Create an instance of {@link CaseRuleReasonCodeType }
     * 
     */
    public CaseRuleReasonCodeType createCaseRuleReasonCodeType() {
        return new CaseRuleReasonCodeType();
    }

    /**
     * Create an instance of {@link CaseRuleActionCodeType }
     * 
     */
    public CaseRuleActionCodeType createCaseRuleActionCodeType() {
        return new CaseRuleActionCodeType();
    }

    /**
     * Create an instance of {@link CaseRule }
     * 
     */
    public CaseRule createCaseRule() {
        return new CaseRule();
    }

    /**
     * Create an instance of {@link MatchingRule }
     * 
     */
    public MatchingRule createMatchingRule() {
        return new MatchingRule();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link SearchCondition }
     * 
     */
    public SearchCondition createSearchCondition() {
        return new SearchCondition();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link CaseHistory }
     * 
     */
    public CaseHistory createCaseHistory() {
        return new CaseHistory();
    }

    /**
     * Create an instance of {@link Disposition }
     * 
     */
    public Disposition createDisposition() {
        return new Disposition();
    }

    /**
     * Create an instance of {@link DecisionResults }
     * 
     */
    public DecisionResults createDecisionResults() {
        return new DecisionResults();
    }

    /**
     * Create an instance of {@link DecisionSummary }
     * 
     */
    public DecisionSummary createDecisionSummary() {
        return new DecisionSummary();
    }

    /**
     * Create an instance of {@link MatchCount }
     * 
     */
    public MatchCount createMatchCount() {
        return new MatchCount();
    }

    /**
     * Create an instance of {@link ServiceInvocation }
     * 
     */
    public ServiceInvocation createServiceInvocation() {
        return new ServiceInvocation();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link ScoreType }
     * 
     */
    public ScoreType createScoreType() {
        return new ScoreType();
    }

    /**
     * Create an instance of {@link ScoreReasonCodeType }
     * 
     */
    public ScoreReasonCodeType createScoreReasonCodeType() {
        return new ScoreReasonCodeType();
    }

    /**
     * Create an instance of {@link CaseCommentType }
     * 
     */
    public CaseCommentType createCaseCommentType() {
        return new CaseCommentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fico.com/fraud/schemas", name = "Case")
    public JAXBElement<CaseType> createCase(CaseType value) {
        return new JAXBElement<CaseType>(_Case_QNAME, CaseType.class, null, value);
    }

}
