//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.fico.afm.model.application.cdac.tu.ParsedResponseList;


/**
 * <p>Java class for TuBureauReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TuBureauReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fico.com/fraud/schemas}BureauReport"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}ParsedResponseList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TuBureauReport", propOrder = {
    "bureauReport"
})
public class TuBureauReport
    extends BureauReport
{

    @XmlElement(name = "ParsedResponseList", namespace = "http://fico.com/dms/fidms/cc/cdac/tu", required = true)
    protected ParsedResponseList bureauReport;

    /**
     * Gets the value of the bureauReport property.
     * 
     * @return
     *     possible object is
     *     {@link ParsedResponseList }
     *     
     */
    public ParsedResponseList getBureauReport() {
        return bureauReport;
    }

    /**
     * Sets the value of the bureauReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParsedResponseList }
     *     
     */
    public void setBureauReport(ParsedResponseList value) {
        this.bureauReport = value;
    }

}
