//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.tu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * TU LK01, SA01, PN01, AO01 segments.
 * 
 * <p>Java class for DirectoryTu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectoryTu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/tu}DirectoryType"&gt;
 *       &lt;attribute name="SubscriberAddress2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BureauMarket" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BureauSubmarket" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SegmentDecoded" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MethodOfContact" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PhoneSourceIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PhoneQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PhoneType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AvailabilityIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProductStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SearchStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectoryTu")
public class DirectoryTu
    extends DirectoryType
{

    @XmlAttribute(name = "SubscriberAddress2")
    protected String subscriberAddress2;
    @XmlAttribute(name = "BureauMarket")
    protected String bureauMarket;
    @XmlAttribute(name = "BureauSubmarket")
    protected String bureauSubmarket;
    @XmlAttribute(name = "IndustryCode")
    protected String industryCode;
    @XmlAttribute(name = "SegmentDecoded")
    protected String segmentDecoded;
    @XmlAttribute(name = "MethodOfContact")
    protected String methodOfContact;
    @XmlAttribute(name = "PhoneSourceIndicator")
    protected String phoneSourceIndicator;
    @XmlAttribute(name = "PhoneQualifier")
    protected String phoneQualifier;
    @XmlAttribute(name = "PhoneType")
    protected String phoneType;
    @XmlAttribute(name = "AvailabilityIndicator")
    protected String availabilityIndicator;
    @XmlAttribute(name = "AreaCode")
    protected String areaCode;
    @XmlAttribute(name = "Extension")
    protected String extension;
    @XmlAttribute(name = "ProductCode")
    protected String productCode;
    @XmlAttribute(name = "ProductStatus")
    protected String productStatus;
    @XmlAttribute(name = "SearchStatus")
    protected String searchStatus;

    /**
     * Gets the value of the subscriberAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberAddress2() {
        return subscriberAddress2;
    }

    /**
     * Sets the value of the subscriberAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberAddress2(String value) {
        this.subscriberAddress2 = value;
    }

    /**
     * Gets the value of the bureauMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauMarket() {
        return bureauMarket;
    }

    /**
     * Sets the value of the bureauMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauMarket(String value) {
        this.bureauMarket = value;
    }

    /**
     * Gets the value of the bureauSubmarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauSubmarket() {
        return bureauSubmarket;
    }

    /**
     * Sets the value of the bureauSubmarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauSubmarket(String value) {
        this.bureauSubmarket = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCode(String value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the segmentDecoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentDecoded() {
        return segmentDecoded;
    }

    /**
     * Sets the value of the segmentDecoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentDecoded(String value) {
        this.segmentDecoded = value;
    }

    /**
     * Gets the value of the methodOfContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodOfContact() {
        return methodOfContact;
    }

    /**
     * Sets the value of the methodOfContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodOfContact(String value) {
        this.methodOfContact = value;
    }

    /**
     * Gets the value of the phoneSourceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneSourceIndicator() {
        return phoneSourceIndicator;
    }

    /**
     * Sets the value of the phoneSourceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneSourceIndicator(String value) {
        this.phoneSourceIndicator = value;
    }

    /**
     * Gets the value of the phoneQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneQualifier() {
        return phoneQualifier;
    }

    /**
     * Sets the value of the phoneQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneQualifier(String value) {
        this.phoneQualifier = value;
    }

    /**
     * Gets the value of the phoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * Sets the value of the phoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneType(String value) {
        this.phoneType = value;
    }

    /**
     * Gets the value of the availabilityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityIndicator() {
        return availabilityIndicator;
    }

    /**
     * Sets the value of the availabilityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityIndicator(String value) {
        this.availabilityIndicator = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * Sets the value of the productStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductStatus(String value) {
        this.productStatus = value;
    }

    /**
     * Gets the value of the searchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchStatus() {
        return searchStatus;
    }

    /**
     * Sets the value of the searchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchStatus(String value) {
        this.searchStatus = value;
    }

}
