//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.tu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}HeaderList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}IdentificationList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}NameOrAliasList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}AddressList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}EmploymentList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}ConsumerStatementList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}PublicRecordList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}CollectionList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}TradelineList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}InquiryList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}BureauInformationList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}ScoringList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}FraudList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}DirectoryList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}SummaryInformationList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}PrintImageList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}MiscellaneousList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}YearOfIssuanceList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/tu}EndSegmentList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ParseWarning" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ApplicantIndex" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerList",
    "identificationList",
    "nameOrAliasList",
    "addressList",
    "employmentList",
    "consumerStatementList",
    "publicRecordList",
    "collectionList",
    "tradelineList",
    "inquiryList",
    "bureauInformationList",
    "scoringList",
    "fraudList",
    "directoryList",
    "summaryInformationList",
    "printImageList",
    "miscellaneousList",
    "yearOfIssuanceList",
    "endSegmentList"
})
@XmlRootElement(name = "ParsedResponse")
public class ParsedResponse {

    @XmlElement(name = "HeaderList")
    protected HeaderList headerList;
    @XmlElement(name = "IdentificationList")
    protected IdentificationList identificationList;
    @XmlElement(name = "NameOrAliasList")
    protected NameOrAliasList nameOrAliasList;
    @XmlElement(name = "AddressList")
    protected AddressList addressList;
    @XmlElement(name = "EmploymentList")
    protected EmploymentList employmentList;
    @XmlElement(name = "ConsumerStatementList")
    protected ConsumerStatementList consumerStatementList;
    @XmlElement(name = "PublicRecordList")
    protected PublicRecordList publicRecordList;
    @XmlElement(name = "CollectionList")
    protected CollectionList collectionList;
    @XmlElement(name = "TradelineList")
    protected TradelineList tradelineList;
    @XmlElement(name = "InquiryList")
    protected InquiryList inquiryList;
    @XmlElement(name = "BureauInformationList")
    protected BureauInformationList bureauInformationList;
    @XmlElement(name = "ScoringList")
    protected ScoringList scoringList;
    @XmlElement(name = "FraudList")
    protected FraudList fraudList;
    @XmlElement(name = "DirectoryList")
    protected DirectoryList directoryList;
    @XmlElement(name = "SummaryInformationList")
    protected SummaryInformationList summaryInformationList;
    @XmlElement(name = "PrintImageList")
    protected PrintImageList printImageList;
    @XmlElement(name = "MiscellaneousList")
    protected MiscellaneousList miscellaneousList;
    @XmlElement(name = "YearOfIssuanceList")
    protected YearOfIssuanceList yearOfIssuanceList;
    @XmlElement(name = "EndSegmentList")
    protected EndSegmentList endSegmentList;
    @XmlAttribute(name = "ParseWarning")
    protected String parseWarning;
    @XmlAttribute(name = "ApplicantIndex")
    protected Integer applicantIndex;

    /**
     * Gets the value of the headerList property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderList }
     *     
     */
    public HeaderList getHeaderList() {
        return headerList;
    }

    /**
     * Sets the value of the headerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderList }
     *     
     */
    public void setHeaderList(HeaderList value) {
        this.headerList = value;
    }

    /**
     * Gets the value of the identificationList property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationList }
     *     
     */
    public IdentificationList getIdentificationList() {
        return identificationList;
    }

    /**
     * Sets the value of the identificationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationList }
     *     
     */
    public void setIdentificationList(IdentificationList value) {
        this.identificationList = value;
    }

    /**
     * Gets the value of the nameOrAliasList property.
     * 
     * @return
     *     possible object is
     *     {@link NameOrAliasList }
     *     
     */
    public NameOrAliasList getNameOrAliasList() {
        return nameOrAliasList;
    }

    /**
     * Sets the value of the nameOrAliasList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameOrAliasList }
     *     
     */
    public void setNameOrAliasList(NameOrAliasList value) {
        this.nameOrAliasList = value;
    }

    /**
     * Gets the value of the addressList property.
     * 
     * @return
     *     possible object is
     *     {@link AddressList }
     *     
     */
    public AddressList getAddressList() {
        return addressList;
    }

    /**
     * Sets the value of the addressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressList }
     *     
     */
    public void setAddressList(AddressList value) {
        this.addressList = value;
    }

    /**
     * Gets the value of the employmentList property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentList }
     *     
     */
    public EmploymentList getEmploymentList() {
        return employmentList;
    }

    /**
     * Sets the value of the employmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentList }
     *     
     */
    public void setEmploymentList(EmploymentList value) {
        this.employmentList = value;
    }

    /**
     * Gets the value of the consumerStatementList property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerStatementList }
     *     
     */
    public ConsumerStatementList getConsumerStatementList() {
        return consumerStatementList;
    }

    /**
     * Sets the value of the consumerStatementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerStatementList }
     *     
     */
    public void setConsumerStatementList(ConsumerStatementList value) {
        this.consumerStatementList = value;
    }

    /**
     * Gets the value of the publicRecordList property.
     * 
     * @return
     *     possible object is
     *     {@link PublicRecordList }
     *     
     */
    public PublicRecordList getPublicRecordList() {
        return publicRecordList;
    }

    /**
     * Sets the value of the publicRecordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicRecordList }
     *     
     */
    public void setPublicRecordList(PublicRecordList value) {
        this.publicRecordList = value;
    }

    /**
     * Gets the value of the collectionList property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionList }
     *     
     */
    public CollectionList getCollectionList() {
        return collectionList;
    }

    /**
     * Sets the value of the collectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionList }
     *     
     */
    public void setCollectionList(CollectionList value) {
        this.collectionList = value;
    }

    /**
     * Gets the value of the tradelineList property.
     * 
     * @return
     *     possible object is
     *     {@link TradelineList }
     *     
     */
    public TradelineList getTradelineList() {
        return tradelineList;
    }

    /**
     * Sets the value of the tradelineList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradelineList }
     *     
     */
    public void setTradelineList(TradelineList value) {
        this.tradelineList = value;
    }

    /**
     * Gets the value of the inquiryList property.
     * 
     * @return
     *     possible object is
     *     {@link InquiryList }
     *     
     */
    public InquiryList getInquiryList() {
        return inquiryList;
    }

    /**
     * Sets the value of the inquiryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquiryList }
     *     
     */
    public void setInquiryList(InquiryList value) {
        this.inquiryList = value;
    }

    /**
     * Gets the value of the bureauInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link BureauInformationList }
     *     
     */
    public BureauInformationList getBureauInformationList() {
        return bureauInformationList;
    }

    /**
     * Sets the value of the bureauInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BureauInformationList }
     *     
     */
    public void setBureauInformationList(BureauInformationList value) {
        this.bureauInformationList = value;
    }

    /**
     * Gets the value of the scoringList property.
     * 
     * @return
     *     possible object is
     *     {@link ScoringList }
     *     
     */
    public ScoringList getScoringList() {
        return scoringList;
    }

    /**
     * Sets the value of the scoringList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoringList }
     *     
     */
    public void setScoringList(ScoringList value) {
        this.scoringList = value;
    }

    /**
     * Gets the value of the fraudList property.
     * 
     * @return
     *     possible object is
     *     {@link FraudList }
     *     
     */
    public FraudList getFraudList() {
        return fraudList;
    }

    /**
     * Sets the value of the fraudList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudList }
     *     
     */
    public void setFraudList(FraudList value) {
        this.fraudList = value;
    }

    /**
     * Gets the value of the directoryList property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryList }
     *     
     */
    public DirectoryList getDirectoryList() {
        return directoryList;
    }

    /**
     * Sets the value of the directoryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryList }
     *     
     */
    public void setDirectoryList(DirectoryList value) {
        this.directoryList = value;
    }

    /**
     * Gets the value of the summaryInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryInformationList }
     *     
     */
    public SummaryInformationList getSummaryInformationList() {
        return summaryInformationList;
    }

    /**
     * Sets the value of the summaryInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryInformationList }
     *     
     */
    public void setSummaryInformationList(SummaryInformationList value) {
        this.summaryInformationList = value;
    }

    /**
     * Gets the value of the printImageList property.
     * 
     * @return
     *     possible object is
     *     {@link PrintImageList }
     *     
     */
    public PrintImageList getPrintImageList() {
        return printImageList;
    }

    /**
     * Sets the value of the printImageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintImageList }
     *     
     */
    public void setPrintImageList(PrintImageList value) {
        this.printImageList = value;
    }

    /**
     * Gets the value of the miscellaneousList property.
     * 
     * @return
     *     possible object is
     *     {@link MiscellaneousList }
     *     
     */
    public MiscellaneousList getMiscellaneousList() {
        return miscellaneousList;
    }

    /**
     * Sets the value of the miscellaneousList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscellaneousList }
     *     
     */
    public void setMiscellaneousList(MiscellaneousList value) {
        this.miscellaneousList = value;
    }

    /**
     * Gets the value of the yearOfIssuanceList property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfIssuanceList }
     *     
     */
    public YearOfIssuanceList getYearOfIssuanceList() {
        return yearOfIssuanceList;
    }

    /**
     * Sets the value of the yearOfIssuanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfIssuanceList }
     *     
     */
    public void setYearOfIssuanceList(YearOfIssuanceList value) {
        this.yearOfIssuanceList = value;
    }

    /**
     * Gets the value of the endSegmentList property.
     * 
     * @return
     *     possible object is
     *     {@link EndSegmentList }
     *     
     */
    public EndSegmentList getEndSegmentList() {
        return endSegmentList;
    }

    /**
     * Sets the value of the endSegmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndSegmentList }
     *     
     */
    public void setEndSegmentList(EndSegmentList value) {
        this.endSegmentList = value;
    }

    /**
     * Gets the value of the parseWarning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParseWarning() {
        return parseWarning;
    }

    /**
     * Sets the value of the parseWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParseWarning(String value) {
        this.parseWarning = value;
    }

    /**
     * Gets the value of the applicantIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getApplicantIndex() {
        return applicantIndex;
    }

    /**
     * Sets the value of the applicantIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setApplicantIndex(Integer value) {
        this.applicantIndex = value;
    }

}
