//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.xpn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * XPN 900, 950 segments.
 * 
 * <p>Java class for EndSegmentXpn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndSegmentXpn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/xpn}EndSegmentType"&gt;
 *       &lt;attribute name="PositiveTradeItems" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NonEvaluatedTradeItems" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NegativeTradeItems" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NonEvaluatedLegalItems" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NegativeLegalItems" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndSegmentXpn")
public class EndSegmentXpn
    extends EndSegmentType
{

    @XmlAttribute(name = "PositiveTradeItems")
    protected String positiveTradeItems;
    @XmlAttribute(name = "NonEvaluatedTradeItems")
    protected String nonEvaluatedTradeItems;
    @XmlAttribute(name = "NegativeTradeItems")
    protected String negativeTradeItems;
    @XmlAttribute(name = "NonEvaluatedLegalItems")
    protected String nonEvaluatedLegalItems;
    @XmlAttribute(name = "NegativeLegalItems")
    protected String negativeLegalItems;

    /**
     * Gets the value of the positiveTradeItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositiveTradeItems() {
        return positiveTradeItems;
    }

    /**
     * Sets the value of the positiveTradeItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositiveTradeItems(String value) {
        this.positiveTradeItems = value;
    }

    /**
     * Gets the value of the nonEvaluatedTradeItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonEvaluatedTradeItems() {
        return nonEvaluatedTradeItems;
    }

    /**
     * Sets the value of the nonEvaluatedTradeItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonEvaluatedTradeItems(String value) {
        this.nonEvaluatedTradeItems = value;
    }

    /**
     * Gets the value of the negativeTradeItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeTradeItems() {
        return negativeTradeItems;
    }

    /**
     * Sets the value of the negativeTradeItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeTradeItems(String value) {
        this.negativeTradeItems = value;
    }

    /**
     * Gets the value of the nonEvaluatedLegalItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonEvaluatedLegalItems() {
        return nonEvaluatedLegalItems;
    }

    /**
     * Sets the value of the nonEvaluatedLegalItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonEvaluatedLegalItems(String value) {
        this.nonEvaluatedLegalItems = value;
    }

    /**
     * Gets the value of the negativeLegalItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeLegalItems() {
        return negativeLegalItems;
    }

    /**
     * Sets the value of the negativeLegalItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeLegalItems(String value) {
        this.negativeLegalItems = value;
    }

}
