//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.xpn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * XPN 382 segment.
 * 
 * <p>Java class for FraudXpn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FraudXpn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/xpn}FraudType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="MessageText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}FraudServicesSsnIssuedList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}FraudServicesIndicatorList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="RecordType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StandardIndustrialClassificationCodes" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SsnDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SsnCounter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SsnErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AddressDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AddressCount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AddressErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DeathDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kSsnDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kAddressDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FraudXpn", propOrder = {
    "messageText",
    "fraudServicesSsnIssuedList",
    "fraudServicesIndicatorList"
})
public class FraudXpn
    extends FraudType
{

    @XmlElement(name = "MessageText")
    protected String messageText;
    @XmlElement(name = "FraudServicesSsnIssuedList")
    protected FraudServicesSsnIssuedList fraudServicesSsnIssuedList;
    @XmlElement(name = "FraudServicesIndicatorList")
    protected FraudServicesIndicatorList fraudServicesIndicatorList;
    @XmlAttribute(name = "RecordType")
    protected String recordType;
    @XmlAttribute(name = "StandardIndustrialClassificationCodes")
    protected String standardIndustrialClassificationCodes;
    @XmlAttribute(name = "SsnDate")
    protected String ssnDate;
    @XmlAttribute(name = "SsnCounter")
    protected String ssnCounter;
    @XmlAttribute(name = "SsnErrorCode")
    protected String ssnErrorCode;
    @XmlAttribute(name = "AddressDate")
    protected String addressDate;
    @XmlAttribute(name = "AddressCount")
    protected String addressCount;
    @XmlAttribute(name = "AddressErrorCode")
    protected String addressErrorCode;
    @XmlAttribute(name = "DateOfBirth")
    protected String dateOfBirth;
    @XmlAttribute(name = "DeathDate")
    protected String deathDate;
    @XmlAttribute(name = "Y2kSsnDate")
    protected String y2KSsnDate;
    @XmlAttribute(name = "Y2kAddressDate")
    protected String y2KAddressDate;

    /**
     * Gets the value of the messageText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageText() {
        return messageText;
    }

    /**
     * Sets the value of the messageText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageText(String value) {
        this.messageText = value;
    }

    /**
     * Gets the value of the fraudServicesSsnIssuedList property.
     * 
     * @return
     *     possible object is
     *     {@link FraudServicesSsnIssuedList }
     *     
     */
    public FraudServicesSsnIssuedList getFraudServicesSsnIssuedList() {
        return fraudServicesSsnIssuedList;
    }

    /**
     * Sets the value of the fraudServicesSsnIssuedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudServicesSsnIssuedList }
     *     
     */
    public void setFraudServicesSsnIssuedList(FraudServicesSsnIssuedList value) {
        this.fraudServicesSsnIssuedList = value;
    }

    /**
     * Gets the value of the fraudServicesIndicatorList property.
     * 
     * @return
     *     possible object is
     *     {@link FraudServicesIndicatorList }
     *     
     */
    public FraudServicesIndicatorList getFraudServicesIndicatorList() {
        return fraudServicesIndicatorList;
    }

    /**
     * Sets the value of the fraudServicesIndicatorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudServicesIndicatorList }
     *     
     */
    public void setFraudServicesIndicatorList(FraudServicesIndicatorList value) {
        this.fraudServicesIndicatorList = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordType(String value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the standardIndustrialClassificationCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardIndustrialClassificationCodes() {
        return standardIndustrialClassificationCodes;
    }

    /**
     * Sets the value of the standardIndustrialClassificationCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardIndustrialClassificationCodes(String value) {
        this.standardIndustrialClassificationCodes = value;
    }

    /**
     * Gets the value of the ssnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsnDate() {
        return ssnDate;
    }

    /**
     * Sets the value of the ssnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsnDate(String value) {
        this.ssnDate = value;
    }

    /**
     * Gets the value of the ssnCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsnCounter() {
        return ssnCounter;
    }

    /**
     * Sets the value of the ssnCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsnCounter(String value) {
        this.ssnCounter = value;
    }

    /**
     * Gets the value of the ssnErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsnErrorCode() {
        return ssnErrorCode;
    }

    /**
     * Sets the value of the ssnErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsnErrorCode(String value) {
        this.ssnErrorCode = value;
    }

    /**
     * Gets the value of the addressDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressDate() {
        return addressDate;
    }

    /**
     * Sets the value of the addressDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressDate(String value) {
        this.addressDate = value;
    }

    /**
     * Gets the value of the addressCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressCount() {
        return addressCount;
    }

    /**
     * Sets the value of the addressCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressCount(String value) {
        this.addressCount = value;
    }

    /**
     * Gets the value of the addressErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressErrorCode() {
        return addressErrorCode;
    }

    /**
     * Sets the value of the addressErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressErrorCode(String value) {
        this.addressErrorCode = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the deathDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathDate() {
        return deathDate;
    }

    /**
     * Sets the value of the deathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathDate(String value) {
        this.deathDate = value;
    }

    /**
     * Gets the value of the y2KSsnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KSsnDate() {
        return y2KSsnDate;
    }

    /**
     * Sets the value of the y2KSsnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KSsnDate(String value) {
        this.y2KSsnDate = value;
    }

    /**
     * Gets the value of the y2KAddressDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KAddressDate() {
        return y2KAddressDate;
    }

    /**
     * Sets the value of the y2KAddressDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KAddressDate(String value) {
        this.y2KAddressDate = value;
    }

}
