//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.xpn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * XPN 100, 110, 200 segments.
 * 
 * <p>Java class for HeaderXpn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderXpn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/xpn}HeaderType"&gt;
 *       &lt;attribute name="HostId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ReportTime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Preamble" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SubjectLastName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SubjectFirstName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ErrorMessageCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ActionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ModuleIdent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kReportDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderXpn")
public class HeaderXpn
    extends HeaderType
{

    @XmlAttribute(name = "HostId")
    protected String hostId;
    @XmlAttribute(name = "ReportTime")
    protected String reportTime;
    @XmlAttribute(name = "Preamble")
    protected String preamble;
    @XmlAttribute(name = "SubjectLastName")
    protected String subjectLastName;
    @XmlAttribute(name = "SubjectFirstName")
    protected String subjectFirstName;
    @XmlAttribute(name = "ErrorMessageCode")
    protected String errorMessageCode;
    @XmlAttribute(name = "ActionIndicator")
    protected String actionIndicator;
    @XmlAttribute(name = "ModuleIdent")
    protected String moduleIdent;
    @XmlAttribute(name = "Y2kReportDate")
    protected String y2KReportDate;

    /**
     * Gets the value of the hostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * Sets the value of the hostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostId(String value) {
        this.hostId = value;
    }

    /**
     * Gets the value of the reportTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportTime() {
        return reportTime;
    }

    /**
     * Sets the value of the reportTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportTime(String value) {
        this.reportTime = value;
    }

    /**
     * Gets the value of the preamble property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreamble() {
        return preamble;
    }

    /**
     * Sets the value of the preamble property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreamble(String value) {
        this.preamble = value;
    }

    /**
     * Gets the value of the subjectLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectLastName() {
        return subjectLastName;
    }

    /**
     * Sets the value of the subjectLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectLastName(String value) {
        this.subjectLastName = value;
    }

    /**
     * Gets the value of the subjectFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectFirstName() {
        return subjectFirstName;
    }

    /**
     * Sets the value of the subjectFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectFirstName(String value) {
        this.subjectFirstName = value;
    }

    /**
     * Gets the value of the errorMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessageCode() {
        return errorMessageCode;
    }

    /**
     * Sets the value of the errorMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessageCode(String value) {
        this.errorMessageCode = value;
    }

    /**
     * Gets the value of the actionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionIndicator() {
        return actionIndicator;
    }

    /**
     * Sets the value of the actionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionIndicator(String value) {
        this.actionIndicator = value;
    }

    /**
     * Gets the value of the moduleIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleIdent() {
        return moduleIdent;
    }

    /**
     * Sets the value of the moduleIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleIdent(String value) {
        this.moduleIdent = value;
    }

    /**
     * Gets the value of the y2KReportDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KReportDate() {
        return y2KReportDate;
    }

    /**
     * Sets the value of the y2KReportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KReportDate(String value) {
        this.y2KReportDate = value;
    }

}
