//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.xpn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * XPN 612-bytes.
 * 
 * <p>Java class for InquiryXpn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InquiryXpn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/xpn}InquiryType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}SubscriberIdList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}CreditGrantorPhoneNumberList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}SubscriberAddressList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LoanAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TermsDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kInquiryDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ControlNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HouseHoldSequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StateCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IndividualSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SpecialComments" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOpened" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsDateOpened" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CreditLimitPrimitive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RatingCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsInquiryDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CreditAmountPrimitive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EnhancedTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InquiryXpn", propOrder = {
    "subscriberIdList",
    "creditGrantorPhoneNumberList",
    "subscriberAddressList"
})
public class InquiryXpn
    extends InquiryType
{

    @XmlElement(name = "SubscriberIdList")
    protected SubscriberIdList subscriberIdList;
    @XmlElement(name = "CreditGrantorPhoneNumberList")
    protected CreditGrantorPhoneNumberList creditGrantorPhoneNumberList;
    @XmlElement(name = "SubscriberAddressList")
    protected SubscriberAddressList subscriberAddressList;
    @XmlAttribute(name = "AccountNumber")
    protected String accountNumber;
    @XmlAttribute(name = "LoanAmount")
    protected String loanAmount;
    @XmlAttribute(name = "TermsDuration")
    protected String termsDuration;
    @XmlAttribute(name = "Y2kInquiryDate")
    protected String y2KInquiryDate;
    @XmlAttribute(name = "ControlNumber")
    protected String controlNumber;
    @XmlAttribute(name = "HouseHoldSequence")
    protected String houseHoldSequence;
    @XmlAttribute(name = "StateCode")
    protected String stateCode;
    @XmlAttribute(name = "IndividualSequenceNumber")
    protected String individualSequenceNumber;
    @XmlAttribute(name = "TransactionId")
    protected String transactionId;
    @XmlAttribute(name = "SpecialComments")
    protected String specialComments;
    @XmlAttribute(name = "DateOpened")
    protected String dateOpened;
    @XmlAttribute(name = "NumberOfMonthsDateOpened")
    protected String numberOfMonthsDateOpened;
    @XmlAttribute(name = "IndustryCode")
    protected String industryCode;
    @XmlAttribute(name = "StatusCode")
    protected String statusCode;
    @XmlAttribute(name = "CreditLimitPrimitive")
    protected String creditLimitPrimitive;
    @XmlAttribute(name = "RatingCode")
    protected String ratingCode;
    @XmlAttribute(name = "NumberOfMonthsInquiryDate")
    protected String numberOfMonthsInquiryDate;
    @XmlAttribute(name = "CreditAmountPrimitive")
    protected String creditAmountPrimitive;
    @XmlAttribute(name = "EnhancedTypeCode")
    protected String enhancedTypeCode;

    /**
     * Gets the value of the subscriberIdList property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriberIdList }
     *     
     */
    public SubscriberIdList getSubscriberIdList() {
        return subscriberIdList;
    }

    /**
     * Sets the value of the subscriberIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriberIdList }
     *     
     */
    public void setSubscriberIdList(SubscriberIdList value) {
        this.subscriberIdList = value;
    }

    /**
     * Gets the value of the creditGrantorPhoneNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link CreditGrantorPhoneNumberList }
     *     
     */
    public CreditGrantorPhoneNumberList getCreditGrantorPhoneNumberList() {
        return creditGrantorPhoneNumberList;
    }

    /**
     * Sets the value of the creditGrantorPhoneNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditGrantorPhoneNumberList }
     *     
     */
    public void setCreditGrantorPhoneNumberList(CreditGrantorPhoneNumberList value) {
        this.creditGrantorPhoneNumberList = value;
    }

    /**
     * Gets the value of the subscriberAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriberAddressList }
     *     
     */
    public SubscriberAddressList getSubscriberAddressList() {
        return subscriberAddressList;
    }

    /**
     * Sets the value of the subscriberAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriberAddressList }
     *     
     */
    public void setSubscriberAddressList(SubscriberAddressList value) {
        this.subscriberAddressList = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the loanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanAmount() {
        return loanAmount;
    }

    /**
     * Sets the value of the loanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanAmount(String value) {
        this.loanAmount = value;
    }

    /**
     * Gets the value of the termsDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsDuration() {
        return termsDuration;
    }

    /**
     * Sets the value of the termsDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsDuration(String value) {
        this.termsDuration = value;
    }

    /**
     * Gets the value of the y2KInquiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KInquiryDate() {
        return y2KInquiryDate;
    }

    /**
     * Sets the value of the y2KInquiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KInquiryDate(String value) {
        this.y2KInquiryDate = value;
    }

    /**
     * Gets the value of the controlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlNumber() {
        return controlNumber;
    }

    /**
     * Sets the value of the controlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlNumber(String value) {
        this.controlNumber = value;
    }

    /**
     * Gets the value of the houseHoldSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseHoldSequence() {
        return houseHoldSequence;
    }

    /**
     * Sets the value of the houseHoldSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseHoldSequence(String value) {
        this.houseHoldSequence = value;
    }

    /**
     * Gets the value of the stateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * Sets the value of the stateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCode(String value) {
        this.stateCode = value;
    }

    /**
     * Gets the value of the individualSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualSequenceNumber() {
        return individualSequenceNumber;
    }

    /**
     * Sets the value of the individualSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualSequenceNumber(String value) {
        this.individualSequenceNumber = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the specialComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialComments() {
        return specialComments;
    }

    /**
     * Sets the value of the specialComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialComments(String value) {
        this.specialComments = value;
    }

    /**
     * Gets the value of the dateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOpened() {
        return dateOpened;
    }

    /**
     * Sets the value of the dateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOpened(String value) {
        this.dateOpened = value;
    }

    /**
     * Gets the value of the numberOfMonthsDateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsDateOpened() {
        return numberOfMonthsDateOpened;
    }

    /**
     * Sets the value of the numberOfMonthsDateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsDateOpened(String value) {
        this.numberOfMonthsDateOpened = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCode(String value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the creditLimitPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimitPrimitive() {
        return creditLimitPrimitive;
    }

    /**
     * Sets the value of the creditLimitPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimitPrimitive(String value) {
        this.creditLimitPrimitive = value;
    }

    /**
     * Gets the value of the ratingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingCode() {
        return ratingCode;
    }

    /**
     * Sets the value of the ratingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingCode(String value) {
        this.ratingCode = value;
    }

    /**
     * Gets the value of the numberOfMonthsInquiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsInquiryDate() {
        return numberOfMonthsInquiryDate;
    }

    /**
     * Sets the value of the numberOfMonthsInquiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsInquiryDate(String value) {
        this.numberOfMonthsInquiryDate = value;
    }

    /**
     * Gets the value of the creditAmountPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditAmountPrimitive() {
        return creditAmountPrimitive;
    }

    /**
     * Sets the value of the creditAmountPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditAmountPrimitive(String value) {
        this.creditAmountPrimitive = value;
    }

    /**
     * Gets the value of the enhancedTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedTypeCode() {
        return enhancedTypeCode;
    }

    /**
     * Sets the value of the enhancedTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedTypeCode(String value) {
        this.enhancedTypeCode = value;
    }

}
