//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 12:07:05 PM PST 
//


package com.fico.afm.model.application.cdac.xpn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * XPN 612-bytes. Legal type.
 * 
 * <p>Java class for PublicRecordXpn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicRecordXpn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fico.com/dms/fidms/cc/cdac/xpn}PublicRecordType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ConsumerComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}CourtNameList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}ReferenceNumberList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}PlaintiffList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}PublicRecordEcoaList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}BankruptcyList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}BookOrPageList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://fico.com/dms/fidms/cc/cdac/xpn}ConsumerDisputeList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Evaluation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VoluntaryInvoluntaryValue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kStatusDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Y2kOriginalFilingDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ControlNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="HouseHoldSequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="StateCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IndividualSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SpecialComments" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOpened" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsDateOpened" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CreditLimitPrimitive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="KindOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AccountType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RatingCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsFilingDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsStatusDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LegalCourtCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LegalStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LegalDateOpened" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DateOfAction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NumberOfMonthsDateOfAction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AccountDesignatorCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CreditAmountPrimitive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EnhancedStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicRecordXpn", propOrder = {
    "consumerComment",
    "courtNameList",
    "referenceNumberList",
    "plaintiffList",
    "publicRecordEcoaList",
    "bankruptcyList",
    "bookOrPageList",
    "consumerDisputeList"
})
public class PublicRecordXpn
    extends PublicRecordType
{

    @XmlElement(name = "ConsumerComment")
    protected String consumerComment;
    @XmlElement(name = "CourtNameList")
    protected CourtNameList courtNameList;
    @XmlElement(name = "ReferenceNumberList")
    protected ReferenceNumberList referenceNumberList;
    @XmlElement(name = "PlaintiffList")
    protected PlaintiffList plaintiffList;
    @XmlElement(name = "PublicRecordEcoaList")
    protected PublicRecordEcoaList publicRecordEcoaList;
    @XmlElement(name = "BankruptcyList")
    protected BankruptcyList bankruptcyList;
    @XmlElement(name = "BookOrPageList")
    protected BookOrPageList bookOrPageList;
    @XmlElement(name = "ConsumerDisputeList")
    protected ConsumerDisputeList consumerDisputeList;
    @XmlAttribute(name = "StatusDate")
    protected String statusDate;
    @XmlAttribute(name = "StatusCode")
    protected String statusCode;
    @XmlAttribute(name = "Amount")
    protected String amount;
    @XmlAttribute(name = "Evaluation")
    protected String evaluation;
    @XmlAttribute(name = "VoluntaryInvoluntaryValue")
    protected String voluntaryInvoluntaryValue;
    @XmlAttribute(name = "Y2kStatusDate")
    protected String y2KStatusDate;
    @XmlAttribute(name = "Y2kOriginalFilingDate")
    protected String y2KOriginalFilingDate;
    @XmlAttribute(name = "ControlNumber")
    protected String controlNumber;
    @XmlAttribute(name = "HouseHoldSequence")
    protected String houseHoldSequence;
    @XmlAttribute(name = "StateCode")
    protected String stateCode;
    @XmlAttribute(name = "IndividualSequenceNumber")
    protected String individualSequenceNumber;
    @XmlAttribute(name = "TransactionId")
    protected String transactionId;
    @XmlAttribute(name = "SpecialComments")
    protected String specialComments;
    @XmlAttribute(name = "DateOpened")
    protected String dateOpened;
    @XmlAttribute(name = "NumberOfMonthsDateOpened")
    protected String numberOfMonthsDateOpened;
    @XmlAttribute(name = "CreditLimitPrimitive")
    protected String creditLimitPrimitive;
    @XmlAttribute(name = "IndustryCode")
    protected String industryCode;
    @XmlAttribute(name = "KindOfBusiness")
    protected String kindOfBusiness;
    @XmlAttribute(name = "AccountType")
    protected String accountType;
    @XmlAttribute(name = "RatingCode")
    protected String ratingCode;
    @XmlAttribute(name = "NumberOfMonthsFilingDate")
    protected String numberOfMonthsFilingDate;
    @XmlAttribute(name = "NumberOfMonthsStatusDate")
    protected String numberOfMonthsStatusDate;
    @XmlAttribute(name = "LegalCourtCode")
    protected String legalCourtCode;
    @XmlAttribute(name = "LegalStatus")
    protected String legalStatus;
    @XmlAttribute(name = "LegalDateOpened")
    protected String legalDateOpened;
    @XmlAttribute(name = "DateOfAction")
    protected String dateOfAction;
    @XmlAttribute(name = "NumberOfMonthsDateOfAction")
    protected String numberOfMonthsDateOfAction;
    @XmlAttribute(name = "AccountDesignatorCode")
    protected String accountDesignatorCode;
    @XmlAttribute(name = "CreditAmountPrimitive")
    protected String creditAmountPrimitive;
    @XmlAttribute(name = "EnhancedStatusCode")
    protected String enhancedStatusCode;

    /**
     * Gets the value of the consumerComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerComment() {
        return consumerComment;
    }

    /**
     * Sets the value of the consumerComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerComment(String value) {
        this.consumerComment = value;
    }

    /**
     * Gets the value of the courtNameList property.
     * 
     * @return
     *     possible object is
     *     {@link CourtNameList }
     *     
     */
    public CourtNameList getCourtNameList() {
        return courtNameList;
    }

    /**
     * Sets the value of the courtNameList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourtNameList }
     *     
     */
    public void setCourtNameList(CourtNameList value) {
        this.courtNameList = value;
    }

    /**
     * Gets the value of the referenceNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberList }
     *     
     */
    public ReferenceNumberList getReferenceNumberList() {
        return referenceNumberList;
    }

    /**
     * Sets the value of the referenceNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberList }
     *     
     */
    public void setReferenceNumberList(ReferenceNumberList value) {
        this.referenceNumberList = value;
    }

    /**
     * Gets the value of the plaintiffList property.
     * 
     * @return
     *     possible object is
     *     {@link PlaintiffList }
     *     
     */
    public PlaintiffList getPlaintiffList() {
        return plaintiffList;
    }

    /**
     * Sets the value of the plaintiffList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaintiffList }
     *     
     */
    public void setPlaintiffList(PlaintiffList value) {
        this.plaintiffList = value;
    }

    /**
     * Gets the value of the publicRecordEcoaList property.
     * 
     * @return
     *     possible object is
     *     {@link PublicRecordEcoaList }
     *     
     */
    public PublicRecordEcoaList getPublicRecordEcoaList() {
        return publicRecordEcoaList;
    }

    /**
     * Sets the value of the publicRecordEcoaList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicRecordEcoaList }
     *     
     */
    public void setPublicRecordEcoaList(PublicRecordEcoaList value) {
        this.publicRecordEcoaList = value;
    }

    /**
     * Gets the value of the bankruptcyList property.
     * 
     * @return
     *     possible object is
     *     {@link BankruptcyList }
     *     
     */
    public BankruptcyList getBankruptcyList() {
        return bankruptcyList;
    }

    /**
     * Sets the value of the bankruptcyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankruptcyList }
     *     
     */
    public void setBankruptcyList(BankruptcyList value) {
        this.bankruptcyList = value;
    }

    /**
     * Gets the value of the bookOrPageList property.
     * 
     * @return
     *     possible object is
     *     {@link BookOrPageList }
     *     
     */
    public BookOrPageList getBookOrPageList() {
        return bookOrPageList;
    }

    /**
     * Sets the value of the bookOrPageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookOrPageList }
     *     
     */
    public void setBookOrPageList(BookOrPageList value) {
        this.bookOrPageList = value;
    }

    /**
     * Gets the value of the consumerDisputeList property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerDisputeList }
     *     
     */
    public ConsumerDisputeList getConsumerDisputeList() {
        return consumerDisputeList;
    }

    /**
     * Sets the value of the consumerDisputeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerDisputeList }
     *     
     */
    public void setConsumerDisputeList(ConsumerDisputeList value) {
        this.consumerDisputeList = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDate(String value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the evaluation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * Sets the value of the evaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvaluation(String value) {
        this.evaluation = value;
    }

    /**
     * Gets the value of the voluntaryInvoluntaryValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoluntaryInvoluntaryValue() {
        return voluntaryInvoluntaryValue;
    }

    /**
     * Sets the value of the voluntaryInvoluntaryValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoluntaryInvoluntaryValue(String value) {
        this.voluntaryInvoluntaryValue = value;
    }

    /**
     * Gets the value of the y2KStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KStatusDate() {
        return y2KStatusDate;
    }

    /**
     * Sets the value of the y2KStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KStatusDate(String value) {
        this.y2KStatusDate = value;
    }

    /**
     * Gets the value of the y2KOriginalFilingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY2KOriginalFilingDate() {
        return y2KOriginalFilingDate;
    }

    /**
     * Sets the value of the y2KOriginalFilingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY2KOriginalFilingDate(String value) {
        this.y2KOriginalFilingDate = value;
    }

    /**
     * Gets the value of the controlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlNumber() {
        return controlNumber;
    }

    /**
     * Sets the value of the controlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlNumber(String value) {
        this.controlNumber = value;
    }

    /**
     * Gets the value of the houseHoldSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseHoldSequence() {
        return houseHoldSequence;
    }

    /**
     * Sets the value of the houseHoldSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseHoldSequence(String value) {
        this.houseHoldSequence = value;
    }

    /**
     * Gets the value of the stateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * Sets the value of the stateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCode(String value) {
        this.stateCode = value;
    }

    /**
     * Gets the value of the individualSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualSequenceNumber() {
        return individualSequenceNumber;
    }

    /**
     * Sets the value of the individualSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualSequenceNumber(String value) {
        this.individualSequenceNumber = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the specialComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialComments() {
        return specialComments;
    }

    /**
     * Sets the value of the specialComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialComments(String value) {
        this.specialComments = value;
    }

    /**
     * Gets the value of the dateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOpened() {
        return dateOpened;
    }

    /**
     * Sets the value of the dateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOpened(String value) {
        this.dateOpened = value;
    }

    /**
     * Gets the value of the numberOfMonthsDateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsDateOpened() {
        return numberOfMonthsDateOpened;
    }

    /**
     * Sets the value of the numberOfMonthsDateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsDateOpened(String value) {
        this.numberOfMonthsDateOpened = value;
    }

    /**
     * Gets the value of the creditLimitPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimitPrimitive() {
        return creditLimitPrimitive;
    }

    /**
     * Sets the value of the creditLimitPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimitPrimitive(String value) {
        this.creditLimitPrimitive = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCode(String value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the kindOfBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKindOfBusiness() {
        return kindOfBusiness;
    }

    /**
     * Sets the value of the kindOfBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKindOfBusiness(String value) {
        this.kindOfBusiness = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the ratingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingCode() {
        return ratingCode;
    }

    /**
     * Sets the value of the ratingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingCode(String value) {
        this.ratingCode = value;
    }

    /**
     * Gets the value of the numberOfMonthsFilingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsFilingDate() {
        return numberOfMonthsFilingDate;
    }

    /**
     * Sets the value of the numberOfMonthsFilingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsFilingDate(String value) {
        this.numberOfMonthsFilingDate = value;
    }

    /**
     * Gets the value of the numberOfMonthsStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsStatusDate() {
        return numberOfMonthsStatusDate;
    }

    /**
     * Sets the value of the numberOfMonthsStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsStatusDate(String value) {
        this.numberOfMonthsStatusDate = value;
    }

    /**
     * Gets the value of the legalCourtCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalCourtCode() {
        return legalCourtCode;
    }

    /**
     * Sets the value of the legalCourtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalCourtCode(String value) {
        this.legalCourtCode = value;
    }

    /**
     * Gets the value of the legalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the legalDateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalDateOpened() {
        return legalDateOpened;
    }

    /**
     * Sets the value of the legalDateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalDateOpened(String value) {
        this.legalDateOpened = value;
    }

    /**
     * Gets the value of the dateOfAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfAction() {
        return dateOfAction;
    }

    /**
     * Sets the value of the dateOfAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfAction(String value) {
        this.dateOfAction = value;
    }

    /**
     * Gets the value of the numberOfMonthsDateOfAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfMonthsDateOfAction() {
        return numberOfMonthsDateOfAction;
    }

    /**
     * Sets the value of the numberOfMonthsDateOfAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfMonthsDateOfAction(String value) {
        this.numberOfMonthsDateOfAction = value;
    }

    /**
     * Gets the value of the accountDesignatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDesignatorCode() {
        return accountDesignatorCode;
    }

    /**
     * Sets the value of the accountDesignatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDesignatorCode(String value) {
        this.accountDesignatorCode = value;
    }

    /**
     * Gets the value of the creditAmountPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditAmountPrimitive() {
        return creditAmountPrimitive;
    }

    /**
     * Sets the value of the creditAmountPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditAmountPrimitive(String value) {
        this.creditAmountPrimitive = value;
    }

    /**
     * Gets the value of the enhancedStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedStatusCode() {
        return enhancedStatusCode;
    }

    /**
     * Sets the value of the enhancedStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedStatusCode(String value) {
        this.enhancedStatusCode = value;
    }

}
